package com.zhidisoft.crm.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import com.zhidisoft.crm.entity.TbCrmProduct;
import com.zhidisoft.crm.entity.TbCrmProductExample;
import com.zhidisoft.crm.vo.PCImagesVO;
import com.zhidisoft.crm.vo.ProductVO;

public interface TbCrmProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @SelectProvider(type=TbCrmProductSqlProvider.class, method="countByExample")
    long countByExample(TbCrmProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @DeleteProvider(type=TbCrmProductSqlProvider.class, method="deleteByExample")
    int deleteByExample(TbCrmProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @Delete({
        "delete from TB_CRM_PRODUCT",
        "where PRODUCTID = #{productid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @Insert({
        "insert into TB_CRM_PRODUCT (PRODUCTID, CATEGORYID, ",
        "NAME, CREATORUSERID, ",
        "COSTPRICE, SUGGESTEDPRICE, ",
        "DEVELOPMENTTEAM, DEVELOPMENTTIME, ",
        "LINK, CREATETIME, ",
        "UPDATETIME, DESCRIPTION)",
        "values (#{productid,jdbcType=VARCHAR}, #{categoryid,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{creatoruserid,jdbcType=VARCHAR}, ",
        "#{costprice,jdbcType=DECIMAL}, #{suggestedprice,jdbcType=DECIMAL}, ",
        "#{developmentteam,jdbcType=VARCHAR}, #{developmenttime,jdbcType=TIMESTAMP}, ",
        "#{link,jdbcType=VARCHAR}, #{createtime,jdbcType=TIMESTAMP}, ",
        "#{updatetime,jdbcType=TIMESTAMP}, #{description,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="select sys_guid() from dual", keyProperty="productid", before=true, resultType=String.class)
    int insert(TbCrmProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @InsertProvider(type=TbCrmProductSqlProvider.class, method="insertSelective")
    @SelectKey(statement="select sys_guid() from dual", keyProperty="productid", before=true, resultType=String.class)
    int insertSelective(TbCrmProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @SelectProvider(type=TbCrmProductSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="PRODUCTID", property="productid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CATEGORYID", property="categoryid", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATORUSERID", property="creatoruserid", jdbcType=JdbcType.VARCHAR),
        @Result(column="COSTPRICE", property="costprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="SUGGESTEDPRICE", property="suggestedprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEVELOPMENTTEAM", property="developmentteam", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEVELOPMENTTIME", property="developmenttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="LINK", property="link", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATETIME", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATETIME", property="updatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR)
    })
    List<TbCrmProduct> selectByExampleWithRowbounds(TbCrmProductExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @SelectProvider(type=TbCrmProductSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="PRODUCTID", property="productid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CATEGORYID", property="categoryid", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATORUSERID", property="creatoruserid", jdbcType=JdbcType.VARCHAR),
        @Result(column="COSTPRICE", property="costprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="SUGGESTEDPRICE", property="suggestedprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEVELOPMENTTEAM", property="developmentteam", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEVELOPMENTTIME", property="developmenttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="LINK", property="link", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATETIME", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATETIME", property="updatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR)
    })
    List<TbCrmProduct> selectByExample(TbCrmProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @Select({
        "select",
        "PRODUCTID, CATEGORYID, NAME, CREATORUSERID, COSTPRICE, SUGGESTEDPRICE, DEVELOPMENTTEAM, ",
        "DEVELOPMENTTIME, LINK, CREATETIME, UPDATETIME, DESCRIPTION",
        "from TB_CRM_PRODUCT",
        "where PRODUCTID = #{productid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="PRODUCTID", property="productid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CATEGORYID", property="categoryid", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATORUSERID", property="creatoruserid", jdbcType=JdbcType.VARCHAR),
        @Result(column="COSTPRICE", property="costprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="SUGGESTEDPRICE", property="suggestedprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEVELOPMENTTEAM", property="developmentteam", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEVELOPMENTTIME", property="developmenttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="LINK", property="link", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATETIME", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATETIME", property="updatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR)
    })
    TbCrmProduct selectByPrimaryKey(String productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @UpdateProvider(type=TbCrmProductSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TbCrmProduct record, @Param("example") TbCrmProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @UpdateProvider(type=TbCrmProductSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TbCrmProduct record, @Param("example") TbCrmProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @UpdateProvider(type=TbCrmProductSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TbCrmProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    @Update({
        "update TB_CRM_PRODUCT",
        "set CATEGORYID = #{categoryid,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "CREATORUSERID = #{creatoruserid,jdbcType=VARCHAR},",
          "COSTPRICE = #{costprice,jdbcType=DECIMAL},",
          "SUGGESTEDPRICE = #{suggestedprice,jdbcType=DECIMAL},",
          "DEVELOPMENTTEAM = #{developmentteam,jdbcType=VARCHAR},",
          "DEVELOPMENTTIME = #{developmenttime,jdbcType=TIMESTAMP},",
          "LINK = #{link,jdbcType=VARCHAR},",
          "CREATETIME = #{createtime,jdbcType=TIMESTAMP},",
          "UPDATETIME = #{updatetime,jdbcType=TIMESTAMP},",
          "DESCRIPTION = #{description,jdbcType=VARCHAR}",
        "where PRODUCTID = #{productid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TbCrmProduct record);
    
    
    
    /**
	 * 手动 分页 ORACLE
	 * 判断日期
	 *  <![CDATA[ 注意 < 转义
	 */
	@Select({"<script>"
			+ "SELECT * "
			,"FROM (SELECT ROWNUM AS rowno,r.* "
			, " FROM("
			, "SELECT p.*, i.ismain FROM TB_CRM_PRODUCT p LEFT JOIN TB_CRM_PRODUCT_IMAGES i ON p.PRODUCTID=i.IMAGESID"
			," <where>"
			,"   <if test='searchText !=null'>"
					+ " p.name like '%${searchText}%'"
			,"   </if>"
			,"   <if test='where1 !=null and where1 == \"week\"'>"
					+ " p.developmenttime between #{whereData1} and #{whereData2}"
			,"   </if>"
			," </where>"
			, " ) r"
			, " <![CDATA[ where ROWNUM <= #{endIndex} ]]>"
			," ) table_alias"
			, " WHERE table_alias.rowno > ${beginIndex}",
			"</script>"})
	List<ProductVO> findPage(@Param("beginIndex")Integer beginIndex,
								@Param("endIndex")Integer endIndex,
								@Param("searchText") String searchText,
								@Param("where1")String where1,
								@Param("whereData1")Date whereData1,
								@Param("whereData2")Date whereData2
			);
	@Select("select c.name as cname,u.username,p.* from TB_CRM_PRODUCT p\n" + 
			"left join tb_crm_product_category c on c.CATEGORYID=p.CATEGORYID\n" + 
			"left join tb_system_user u on u.id=p.creatoruserid\n" + 
			"\n" + 
			"where p.PRODUCTID= #{productid}")
	PCImagesVO  findVO( String productid);
    
}