package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbCrmCustomer;
import com.zhidisoft.crm.entity.TbCrmCustomerExample.Criteria;
import com.zhidisoft.crm.entity.TbCrmCustomerExample.Criterion;
import com.zhidisoft.crm.entity.TbCrmCustomerExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TbCrmCustomerSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	public String countByExample(TbCrmCustomerExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("TB_CRM_CUSTOMER");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	public String deleteByExample(TbCrmCustomerExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("TB_CRM_CUSTOMER");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	public String insertSelective(TbCrmCustomer record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("TB_CRM_CUSTOMER");
		sql.VALUES("CUSTOMERID", "#{customerid,jdbcType=VARCHAR}");
		if (record.getOwneruserid() != null) {
			sql.VALUES("OWNERUSERID", "#{owneruserid,jdbcType=VARCHAR}");
		}
		if (record.getCreatoruserid() != null) {
			sql.VALUES("CREATORUSERID", "#{creatoruserid,jdbcType=VARCHAR}");
		}
		if (record.getName() != null) {
			sql.VALUES("NAME", "#{name,jdbcType=VARCHAR}");
		}
		if (record.getOrigin() != null) {
			sql.VALUES("ORIGIN", "#{origin,jdbcType=VARCHAR}");
		}
		if (record.getAddress() != null) {
			sql.VALUES("ADDRESS", "#{address,jdbcType=VARCHAR}");
		}
		if (record.getZipcode() != null) {
			sql.VALUES("ZIPCODE", "#{zipcode,jdbcType=VARCHAR}");
		}
		if (record.getIndustry() != null) {
			sql.VALUES("INDUSTRY", "#{industry,jdbcType=VARCHAR}");
		}
		if (record.getAnnualrevenue() != null) {
			sql.VALUES("ANNUALREVENUE", "#{annualrevenue,jdbcType=VARCHAR}");
		}
		if (record.getOwnership() != null) {
			sql.VALUES("OWNERSHIP", "#{ownership,jdbcType=VARCHAR}");
		}
		if (record.getRating() != null) {
			sql.VALUES("RATING", "#{rating,jdbcType=VARCHAR}");
		}
		if (record.getCreatetime() != null) {
			sql.VALUES("CREATETIME", "#{createtime,jdbcType=TIMESTAMP}");
		}
		if (record.getUpdatetime() != null) {
			sql.VALUES("UPDATETIME", "#{updatetime,jdbcType=TIMESTAMP}");
		}
		if (record.getIsdeleted() != null) {
			sql.VALUES("ISDELETED", "#{isdeleted,jdbcType=DECIMAL}");
		}
		if (record.getIslocked() != null) {
			sql.VALUES("ISLOCKED", "#{islocked,jdbcType=DECIMAL}");
		}
		if (record.getDeleteuserid() != null) {
			sql.VALUES("DELETEUSERID", "#{deleteuserid,jdbcType=VARCHAR}");
		}
		if (record.getDeletetime() != null) {
			sql.VALUES("DELETETIME", "#{deletetime,jdbcType=TIMESTAMP}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	public String selectByExample(TbCrmCustomerExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("CUSTOMERID");
		} else {
			sql.SELECT("CUSTOMERID");
		}
		sql.SELECT("OWNERUSERID");
		sql.SELECT("CREATORUSERID");
		sql.SELECT("NAME");
		sql.SELECT("ORIGIN");
		sql.SELECT("ADDRESS");
		sql.SELECT("ZIPCODE");
		sql.SELECT("INDUSTRY");
		sql.SELECT("ANNUALREVENUE");
		sql.SELECT("OWNERSHIP");
		sql.SELECT("RATING");
		sql.SELECT("CREATETIME");
		sql.SELECT("UPDATETIME");
		sql.SELECT("ISDELETED");
		sql.SELECT("ISLOCKED");
		sql.SELECT("DELETEUSERID");
		sql.SELECT("DELETETIME");
		sql.FROM("TB_CRM_CUSTOMER");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		TbCrmCustomer record = (TbCrmCustomer) parameter.get("record");
		TbCrmCustomerExample example = (TbCrmCustomerExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("TB_CRM_CUSTOMER");
		if (record.getCustomerid() != null) {
			sql.SET("CUSTOMERID = #{record.customerid,jdbcType=VARCHAR}");
		}
		if (record.getOwneruserid() != null) {
			sql.SET("OWNERUSERID = #{record.owneruserid,jdbcType=VARCHAR}");
		}
		if (record.getCreatoruserid() != null) {
			sql.SET("CREATORUSERID = #{record.creatoruserid,jdbcType=VARCHAR}");
		}
		if (record.getName() != null) {
			sql.SET("NAME = #{record.name,jdbcType=VARCHAR}");
		}
		if (record.getOrigin() != null) {
			sql.SET("ORIGIN = #{record.origin,jdbcType=VARCHAR}");
		}
		if (record.getAddress() != null) {
			sql.SET("ADDRESS = #{record.address,jdbcType=VARCHAR}");
		}
		if (record.getZipcode() != null) {
			sql.SET("ZIPCODE = #{record.zipcode,jdbcType=VARCHAR}");
		}
		if (record.getIndustry() != null) {
			sql.SET("INDUSTRY = #{record.industry,jdbcType=VARCHAR}");
		}
		if (record.getAnnualrevenue() != null) {
			sql.SET("ANNUALREVENUE = #{record.annualrevenue,jdbcType=VARCHAR}");
		}
		if (record.getOwnership() != null) {
			sql.SET("OWNERSHIP = #{record.ownership,jdbcType=VARCHAR}");
		}
		if (record.getRating() != null) {
			sql.SET("RATING = #{record.rating,jdbcType=VARCHAR}");
		}
		if (record.getCreatetime() != null) {
			sql.SET("CREATETIME = #{record.createtime,jdbcType=TIMESTAMP}");
		}
		if (record.getUpdatetime() != null) {
			sql.SET("UPDATETIME = #{record.updatetime,jdbcType=TIMESTAMP}");
		}
		if (record.getIsdeleted() != null) {
			sql.SET("ISDELETED = #{record.isdeleted,jdbcType=DECIMAL}");
		}
		if (record.getIslocked() != null) {
			sql.SET("ISLOCKED = #{record.islocked,jdbcType=DECIMAL}");
		}
		if (record.getDeleteuserid() != null) {
			sql.SET("DELETEUSERID = #{record.deleteuserid,jdbcType=VARCHAR}");
		}
		if (record.getDeletetime() != null) {
			sql.SET("DELETETIME = #{record.deletetime,jdbcType=TIMESTAMP}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("TB_CRM_CUSTOMER");
		sql.SET("CUSTOMERID = #{record.customerid,jdbcType=VARCHAR}");
		sql.SET("OWNERUSERID = #{record.owneruserid,jdbcType=VARCHAR}");
		sql.SET("CREATORUSERID = #{record.creatoruserid,jdbcType=VARCHAR}");
		sql.SET("NAME = #{record.name,jdbcType=VARCHAR}");
		sql.SET("ORIGIN = #{record.origin,jdbcType=VARCHAR}");
		sql.SET("ADDRESS = #{record.address,jdbcType=VARCHAR}");
		sql.SET("ZIPCODE = #{record.zipcode,jdbcType=VARCHAR}");
		sql.SET("INDUSTRY = #{record.industry,jdbcType=VARCHAR}");
		sql.SET("ANNUALREVENUE = #{record.annualrevenue,jdbcType=VARCHAR}");
		sql.SET("OWNERSHIP = #{record.ownership,jdbcType=VARCHAR}");
		sql.SET("RATING = #{record.rating,jdbcType=VARCHAR}");
		sql.SET("CREATETIME = #{record.createtime,jdbcType=TIMESTAMP}");
		sql.SET("UPDATETIME = #{record.updatetime,jdbcType=TIMESTAMP}");
		sql.SET("ISDELETED = #{record.isdeleted,jdbcType=DECIMAL}");
		sql.SET("ISLOCKED = #{record.islocked,jdbcType=DECIMAL}");
		sql.SET("DELETEUSERID = #{record.deleteuserid,jdbcType=VARCHAR}");
		sql.SET("DELETETIME = #{record.deletetime,jdbcType=TIMESTAMP}");
		TbCrmCustomerExample example = (TbCrmCustomerExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	public String updateByPrimaryKeySelective(TbCrmCustomer record) {
		SQL sql = new SQL();
		sql.UPDATE("TB_CRM_CUSTOMER");
		if (record.getOwneruserid() != null) {
			sql.SET("OWNERUSERID = #{owneruserid,jdbcType=VARCHAR}");
		}
		if (record.getCreatoruserid() != null) {
			sql.SET("CREATORUSERID = #{creatoruserid,jdbcType=VARCHAR}");
		}
		if (record.getName() != null) {
			sql.SET("NAME = #{name,jdbcType=VARCHAR}");
		}
		if (record.getOrigin() != null) {
			sql.SET("ORIGIN = #{origin,jdbcType=VARCHAR}");
		}
		if (record.getAddress() != null) {
			sql.SET("ADDRESS = #{address,jdbcType=VARCHAR}");
		}
		if (record.getZipcode() != null) {
			sql.SET("ZIPCODE = #{zipcode,jdbcType=VARCHAR}");
		}
		if (record.getIndustry() != null) {
			sql.SET("INDUSTRY = #{industry,jdbcType=VARCHAR}");
		}
		if (record.getAnnualrevenue() != null) {
			sql.SET("ANNUALREVENUE = #{annualrevenue,jdbcType=VARCHAR}");
		}
		if (record.getOwnership() != null) {
			sql.SET("OWNERSHIP = #{ownership,jdbcType=VARCHAR}");
		}
		if (record.getRating() != null) {
			sql.SET("RATING = #{rating,jdbcType=VARCHAR}");
		}
		if (record.getCreatetime() != null) {
			sql.SET("CREATETIME = #{createtime,jdbcType=TIMESTAMP}");
		}
		if (record.getUpdatetime() != null) {
			sql.SET("UPDATETIME = #{updatetime,jdbcType=TIMESTAMP}");
		}
		if (record.getIsdeleted() != null) {
			sql.SET("ISDELETED = #{isdeleted,jdbcType=DECIMAL}");
		}
		if (record.getIslocked() != null) {
			sql.SET("ISLOCKED = #{islocked,jdbcType=DECIMAL}");
		}
		if (record.getDeleteuserid() != null) {
			sql.SET("DELETEUSERID = #{deleteuserid,jdbcType=VARCHAR}");
		}
		if (record.getDeletetime() != null) {
			sql.SET("DELETETIME = #{deletetime,jdbcType=TIMESTAMP}");
		}
		sql.WHERE("CUSTOMERID = #{customerid,jdbcType=VARCHAR}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	protected void applyWhere(SQL sql, TbCrmCustomerExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}