package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbCrmBusiness;
import com.zhidisoft.crm.entity.TbCrmBusinessExample;
import com.zhidisoft.crm.entity.TbCrmBusinessStatus;
import com.zhidisoft.crm.vo.TbCrmBusinessVO;
import com.zhidisoft.crm.vo.FourVO;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TbCrmBusinessMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@SelectProvider(type = TbCrmBusinessSqlProvider.class, method = "countByExample")
	long countByExample(TbCrmBusinessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@DeleteProvider(type = TbCrmBusinessSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbCrmBusinessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@Delete({ "delete from TB_CRM_BUSINESS", "where BUSINESSID = #{businessid,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String businessid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@Insert({ "insert into TB_CRM_BUSINESS (BUSINESSID, NAME, ", "ORIGIN, TYPE, ESTIMATEPRICE, ",
			"CUSTOMERID, CREATORUSERID, ", "OWNERUSERID, GAINRATE, ", "TOTALAMOUNT, SUBTOTALVAL, ",
			"DISCOUNTPRICE, SALESPRICE, ", "DUEDATE, CREATETIME, ", "UPDATETIME, UPDATEUSERID, ",
			"STATUSID, TOTALPRICE, ", "NEXTSTEP, NEXTSTEPTIME, ", "ISDELETED, DELETEUSERID, ",
			"DELETETIME, CONTACTSID, ", "CONTRACTADDRESS, DESCRIPTION)",
			"values (#{businessid,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
			"#{origin,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, #{estimateprice,jdbcType=DECIMAL}, ",
			"#{customerid,jdbcType=VARCHAR}, #{creatoruserid,jdbcType=VARCHAR}, ",
			"#{owneruserid,jdbcType=VARCHAR}, #{gainrate,jdbcType=DECIMAL}, ",
			"#{totalamount,jdbcType=DECIMAL}, #{subtotalval,jdbcType=DECIMAL}, ",
			"#{discountprice,jdbcType=DECIMAL}, #{salesprice,jdbcType=DECIMAL}, ",
			"#{duedate,jdbcType=TIMESTAMP}, #{createtime,jdbcType=TIMESTAMP}, ",
			"#{updatetime,jdbcType=TIMESTAMP}, #{updateuserid,jdbcType=VARCHAR}, ",
			"#{statusid,jdbcType=VARCHAR}, #{totalprice,jdbcType=DECIMAL}, ",
			"#{nextstep,jdbcType=VARCHAR}, #{nextsteptime,jdbcType=TIMESTAMP}, ",
			"#{isdeleted,jdbcType=DECIMAL}, #{deleteuserid,jdbcType=VARCHAR}, ",
			"#{deletetime,jdbcType=TIMESTAMP}, #{contactsid,jdbcType=VARCHAR}, ",
			"#{contractaddress,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR})" })
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "businessid", before = true, resultType = String.class)
	int insert(TbCrmBusiness record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@InsertProvider(type = TbCrmBusinessSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "businessid", before = true, resultType = String.class)
	int insertSelective(TbCrmBusiness record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@SelectProvider(type = TbCrmBusinessSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "BUSINESSID", property = "businessid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ORIGIN", property = "origin", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TYPE", property = "type", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ESTIMATEPRICE", property = "estimateprice", jdbcType = JdbcType.DECIMAL),
			@Result(column = "CUSTOMERID", property = "customerid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATORUSERID", property = "creatoruserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "OWNERUSERID", property = "owneruserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "GAINRATE", property = "gainrate", jdbcType = JdbcType.DECIMAL),
			@Result(column = "TOTALAMOUNT", property = "totalamount", jdbcType = JdbcType.DECIMAL),
			@Result(column = "SUBTOTALVAL", property = "subtotalval", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DISCOUNTPRICE", property = "discountprice", jdbcType = JdbcType.DECIMAL),
			@Result(column = "SALESPRICE", property = "salesprice", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DUEDATE", property = "duedate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "UPDATEUSERID", property = "updateuserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "STATUSID", property = "statusid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TOTALPRICE", property = "totalprice", jdbcType = JdbcType.DECIMAL),
			@Result(column = "NEXTSTEP", property = "nextstep", jdbcType = JdbcType.VARCHAR),
			@Result(column = "NEXTSTEPTIME", property = "nextsteptime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ISDELETED", property = "isdeleted", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DELETEUSERID", property = "deleteuserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DELETETIME", property = "deletetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CONTACTSID", property = "contactsid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CONTRACTADDRESS", property = "contractaddress", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DESCRIPTION", property = "description", jdbcType = JdbcType.VARCHAR) })
	List<TbCrmBusiness> selectByExample(TbCrmBusinessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@Select({ "select", "BUSINESSID, NAME, ORIGIN, TYPE, ESTIMATEPRICE, CUSTOMERID, CREATORUSERID, OWNERUSERID, ",
			"GAINRATE, TOTALAMOUNT, SUBTOTALVAL, DISCOUNTPRICE, SALESPRICE, DUEDATE, CREATETIME, ",
			"UPDATETIME, UPDATEUSERID, STATUSID, TOTALPRICE, NEXTSTEP, NEXTSTEPTIME, ISDELETED, ",
			"DELETEUSERID, DELETETIME, CONTACTSID, CONTRACTADDRESS, DESCRIPTION", "from TB_CRM_BUSINESS",
			"where BUSINESSID = #{businessid,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "BUSINESSID", property = "businessid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ORIGIN", property = "origin", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TYPE", property = "type", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ESTIMATEPRICE", property = "estimateprice", jdbcType = JdbcType.DECIMAL),
			@Result(column = "CUSTOMERID", property = "customerid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATORUSERID", property = "creatoruserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "OWNERUSERID", property = "owneruserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "GAINRATE", property = "gainrate", jdbcType = JdbcType.DECIMAL),
			@Result(column = "TOTALAMOUNT", property = "totalamount", jdbcType = JdbcType.DECIMAL),
			@Result(column = "SUBTOTALVAL", property = "subtotalval", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DISCOUNTPRICE", property = "discountprice", jdbcType = JdbcType.DECIMAL),
			@Result(column = "SALESPRICE", property = "salesprice", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DUEDATE", property = "duedate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "UPDATEUSERID", property = "updateuserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "STATUSID", property = "statusid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TOTALPRICE", property = "totalprice", jdbcType = JdbcType.DECIMAL),
			@Result(column = "NEXTSTEP", property = "nextstep", jdbcType = JdbcType.VARCHAR),
			@Result(column = "NEXTSTEPTIME", property = "nextsteptime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ISDELETED", property = "isdeleted", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DELETEUSERID", property = "deleteuserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DELETETIME", property = "deletetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CONTACTSID", property = "contactsid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CONTRACTADDRESS", property = "contractaddress", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DESCRIPTION", property = "description", jdbcType = JdbcType.VARCHAR) })
	TbCrmBusiness selectByPrimaryKey(String businessid);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@UpdateProvider(type = TbCrmBusinessSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TbCrmBusiness record, @Param("example") TbCrmBusinessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@UpdateProvider(type = TbCrmBusinessSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TbCrmBusiness record, @Param("example") TbCrmBusinessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@UpdateProvider(type = TbCrmBusinessSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TbCrmBusiness record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	@Update({ "update TB_CRM_BUSINESS", "set NAME = #{name,jdbcType=VARCHAR},", "ORIGIN = #{origin,jdbcType=VARCHAR},",
			"TYPE = #{type,jdbcType=VARCHAR},", "ESTIMATEPRICE = #{estimateprice,jdbcType=DECIMAL},",
			"CUSTOMERID = #{customerid,jdbcType=VARCHAR},", "CREATORUSERID = #{creatoruserid,jdbcType=VARCHAR},",
			"OWNERUSERID = #{owneruserid,jdbcType=VARCHAR},", "GAINRATE = #{gainrate,jdbcType=DECIMAL},",
			"TOTALAMOUNT = #{totalamount,jdbcType=DECIMAL},", "SUBTOTALVAL = #{subtotalval,jdbcType=DECIMAL},",
			"DISCOUNTPRICE = #{discountprice,jdbcType=DECIMAL},", "SALESPRICE = #{salesprice,jdbcType=DECIMAL},",
			"DUEDATE = #{duedate,jdbcType=TIMESTAMP},", "CREATETIME = #{createtime,jdbcType=TIMESTAMP},",
			"UPDATETIME = #{updatetime,jdbcType=TIMESTAMP},", "UPDATEUSERID = #{updateuserid,jdbcType=VARCHAR},",
			"STATUSID = #{statusid,jdbcType=VARCHAR},", "TOTALPRICE = #{totalprice,jdbcType=DECIMAL},",
			"NEXTSTEP = #{nextstep,jdbcType=VARCHAR},", "NEXTSTEPTIME = #{nextsteptime,jdbcType=TIMESTAMP},",
			"ISDELETED = #{isdeleted,jdbcType=DECIMAL},", "DELETEUSERID = #{deleteuserid,jdbcType=VARCHAR},",
			"DELETETIME = #{deletetime,jdbcType=TIMESTAMP},", "CONTACTSID = #{contactsid,jdbcType=VARCHAR},",
			"CONTRACTADDRESS = #{contractaddress,jdbcType=VARCHAR},", "DESCRIPTION = #{description,jdbcType=VARCHAR}",
			"where BUSINESSID = #{businessid,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(TbCrmBusiness record);
	
	/*手动分页*/
	
	@Select({ "<script>" 
			+ "SELECT * "
			, "FROM (SELECT ROWNUM AS rowno,r.* "
			, " FROM("
			,"select c.name as names,u.username,b.* from tb_crm_business b left join tb_system_user u on b.OWNERUSERID=u.id left join tb_crm_customer c on c.customerid=b.customerid"
				
			, " <where>"
			,"   <if test='searchText !=null and searchText !=\"\"'>"
					+ " b.name like '%${searchText}%'"
			, "   </if>"
			,"   <if test='where1 !=null and where1 == \"week\"'>"
					+ " b.createtime between #{whereData1} and #{whereData2}"
			,"   </if>"
			, " </where>"
			, " ) r"
			," <![CDATA[ where ROWNUM <= #{endIndex} ]]>"
			, " ) table_alias"
			, " WHERE table_alias.rowno > ${beginIndex}"
			,"</script>" })
	public List<TbCrmBusinessVO> findPage(@Param("beginIndex") Integer beginIndex,
										  @Param("endIndex") Integer endIndex,
										  @Param("searchText") String searchText,
										  @Param("where1")String where1,
										 @Param("whereData1")Date whereData1,
										 @Param("whereData2")Date whereData2);
	
	
	/*关联四张表*/
	@Select("select c.name as customername,u.username,s.name as statusname,co.name as contactsname,	b.* from TB_CRM_BUSINESS b left join tb_system_user u on u.id=b.OWNERUSERID left join tb_crm_customer c on c.customerid=b.customerid left join TB_CRM_BUSINESS_STATUS s on s.statusid=b.statusid	left join TB_CRM_CONTACTS co on co.contactsid=b.contactsid where b.BUSINESSID = #{businessid}")
	FourVO fourById(String businessid);
	
	
	/*关联查询时间内容*/
	@Select("select s.name as statusname,s.description,b.nextstep,b.nextsteptime FROM TB_CRM_BUSINESS b LEFT JOIN TB_CRM_BUSINESS_STATUS s on b.statusid=s.statusid where b.STATUSID = #{statusid}")
	TbCrmBusinessStatus statusById(String businessid);
	
	
}


    	
    