package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbCrmCustomer;
import com.zhidisoft.crm.entity.TbCrmCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TbCrmCustomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@SelectProvider(type = TbCrmCustomerSqlProvider.class, method = "countByExample")
	long countByExample(TbCrmCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@DeleteProvider(type = TbCrmCustomerSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbCrmCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@Delete({ "delete from TB_CRM_CUSTOMER", "where CUSTOMERID = #{customerid,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String customerid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@Insert({ "insert into TB_CRM_CUSTOMER (CUSTOMERID, OWNERUSERID, ", "CREATORUSERID, NAME, ", "ORIGIN, ADDRESS, ",
			"ZIPCODE, INDUSTRY, ", "ANNUALREVENUE, OWNERSHIP, ", "RATING, CREATETIME, ", "UPDATETIME, ISDELETED, ",
			"ISLOCKED, DELETEUSERID, ", "DELETETIME)",
			"values (#{customerid,jdbcType=VARCHAR}, #{owneruserid,jdbcType=VARCHAR}, ",
			"#{creatoruserid,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
			"#{origin,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
			"#{zipcode,jdbcType=VARCHAR}, #{industry,jdbcType=VARCHAR}, ",
			"#{annualrevenue,jdbcType=VARCHAR}, #{ownership,jdbcType=VARCHAR}, ",
			"#{rating,jdbcType=VARCHAR}, #{createtime,jdbcType=TIMESTAMP}, ",
			"#{updatetime,jdbcType=TIMESTAMP}, #{isdeleted,jdbcType=DECIMAL}, ",
			"#{islocked,jdbcType=DECIMAL}, #{deleteuserid,jdbcType=VARCHAR}, ", "#{deletetime,jdbcType=TIMESTAMP})" })
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "customerid", before = true, resultType = String.class)
	int insert(TbCrmCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@InsertProvider(type = TbCrmCustomerSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "customerid", before = true, resultType = String.class)
	int insertSelective(TbCrmCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@SelectProvider(type = TbCrmCustomerSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "CUSTOMERID", property = "customerid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "OWNERUSERID", property = "owneruserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATORUSERID", property = "creatoruserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ORIGIN", property = "origin", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ADDRESS", property = "address", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ZIPCODE", property = "zipcode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "INDUSTRY", property = "industry", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ANNUALREVENUE", property = "annualrevenue", jdbcType = JdbcType.VARCHAR),
			@Result(column = "OWNERSHIP", property = "ownership", jdbcType = JdbcType.VARCHAR),
			@Result(column = "RATING", property = "rating", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ISDELETED", property = "isdeleted", jdbcType = JdbcType.DECIMAL),
			@Result(column = "ISLOCKED", property = "islocked", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DELETEUSERID", property = "deleteuserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DELETETIME", property = "deletetime", jdbcType = JdbcType.TIMESTAMP) })
	List<TbCrmCustomer> selectByExample(TbCrmCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@Select({ "select", "CUSTOMERID, OWNERUSERID, CREATORUSERID, NAME, ORIGIN, ADDRESS, ZIPCODE, INDUSTRY, ",
			"ANNUALREVENUE, OWNERSHIP, RATING, CREATETIME, UPDATETIME, ISDELETED, ISLOCKED, ",
			"DELETEUSERID, DELETETIME", "from TB_CRM_CUSTOMER", "where CUSTOMERID = #{customerid,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "CUSTOMERID", property = "customerid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "OWNERUSERID", property = "owneruserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATORUSERID", property = "creatoruserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ORIGIN", property = "origin", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ADDRESS", property = "address", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ZIPCODE", property = "zipcode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "INDUSTRY", property = "industry", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ANNUALREVENUE", property = "annualrevenue", jdbcType = JdbcType.VARCHAR),
			@Result(column = "OWNERSHIP", property = "ownership", jdbcType = JdbcType.VARCHAR),
			@Result(column = "RATING", property = "rating", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ISDELETED", property = "isdeleted", jdbcType = JdbcType.DECIMAL),
			@Result(column = "ISLOCKED", property = "islocked", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DELETEUSERID", property = "deleteuserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DELETETIME", property = "deletetime", jdbcType = JdbcType.TIMESTAMP) })
	TbCrmCustomer selectByPrimaryKey(String customerid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@UpdateProvider(type = TbCrmCustomerSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TbCrmCustomer record, @Param("example") TbCrmCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@UpdateProvider(type = TbCrmCustomerSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TbCrmCustomer record, @Param("example") TbCrmCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@UpdateProvider(type = TbCrmCustomerSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TbCrmCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CUSTOMER
	 * @mbg.generated  Thu Apr 26 11:59:43 CST 2018
	 */
	@Update({ "update TB_CRM_CUSTOMER", "set OWNERUSERID = #{owneruserid,jdbcType=VARCHAR},",
			"CREATORUSERID = #{creatoruserid,jdbcType=VARCHAR},", "NAME = #{name,jdbcType=VARCHAR},",
			"ORIGIN = #{origin,jdbcType=VARCHAR},", "ADDRESS = #{address,jdbcType=VARCHAR},",
			"ZIPCODE = #{zipcode,jdbcType=VARCHAR},", "INDUSTRY = #{industry,jdbcType=VARCHAR},",
			"ANNUALREVENUE = #{annualrevenue,jdbcType=VARCHAR},", "OWNERSHIP = #{ownership,jdbcType=VARCHAR},",
			"RATING = #{rating,jdbcType=VARCHAR},", "CREATETIME = #{createtime,jdbcType=TIMESTAMP},",
			"UPDATETIME = #{updatetime,jdbcType=TIMESTAMP},", "ISDELETED = #{isdeleted,jdbcType=DECIMAL},",
			"ISLOCKED = #{islocked,jdbcType=DECIMAL},", "DELETEUSERID = #{deleteuserid,jdbcType=VARCHAR},",
			"DELETETIME = #{deletetime,jdbcType=TIMESTAMP}", "where CUSTOMERID = #{customerid,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(TbCrmCustomer record);
}