package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbCrmContacts;
import com.zhidisoft.crm.entity.TbCrmContactsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TbCrmContactsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@SelectProvider(type = TbCrmContactsSqlProvider.class, method = "countByExample")
	long countByExample(TbCrmContactsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@DeleteProvider(type = TbCrmContactsSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbCrmContactsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@Delete({ "delete from TB_CRM_CONTACTS", "where CONTACTSID = #{contactsid,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String contactsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@Insert({ "insert into TB_CRM_CONTACTS (CONTACTSID, CREATORUSERID, ", "NAME, POST, DEPARTMENT, ",
			"SEX, SALTNAME, TELEPHONE, ", "EMAIL, QQNO, ADDRESS, ", "ZIPCODE, DESCRIPTION, ",
			"CREATETIME, UPDATDTIME, ", "ISDELETED, DELETEUSERID, ", "DELETETIME, CUSTOMERID, ",
			"FIRSTCONTACTSID, ISFIRST)", "values (#{contactsid,jdbcType=VARCHAR}, #{creatoruserid,jdbcType=VARCHAR}, ",
			"#{name,jdbcType=VARCHAR}, #{post,jdbcType=VARCHAR}, #{department,jdbcType=VARCHAR}, ",
			"#{sex,jdbcType=DECIMAL}, #{saltname,jdbcType=VARCHAR}, #{telephone,jdbcType=VARCHAR}, ",
			"#{email,jdbcType=VARCHAR}, #{qqno,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
			"#{zipcode,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
			"#{createtime,jdbcType=TIMESTAMP}, #{updatdtime,jdbcType=TIMESTAMP}, ",
			"#{isdeleted,jdbcType=DECIMAL}, #{deleteuserid,jdbcType=VARCHAR}, ",
			"#{deletetime,jdbcType=TIMESTAMP}, #{customerid,jdbcType=VARCHAR}, ",
			"#{firstcontactsid,jdbcType=VARCHAR}, #{isfirst,jdbcType=DECIMAL})" })
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "contactsid", before = true, resultType = String.class)
	int insert(TbCrmContacts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@InsertProvider(type = TbCrmContactsSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "contactsid", before = true, resultType = String.class)
	int insertSelective(TbCrmContacts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@SelectProvider(type = TbCrmContactsSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "CONTACTSID", property = "contactsid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATORUSERID", property = "creatoruserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "POST", property = "post", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DEPARTMENT", property = "department", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SEX", property = "sex", jdbcType = JdbcType.DECIMAL),
			@Result(column = "SALTNAME", property = "saltname", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TELEPHONE", property = "telephone", jdbcType = JdbcType.VARCHAR),
			@Result(column = "EMAIL", property = "email", jdbcType = JdbcType.VARCHAR),
			@Result(column = "QQNO", property = "qqno", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ADDRESS", property = "address", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ZIPCODE", property = "zipcode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DESCRIPTION", property = "description", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "UPDATDTIME", property = "updatdtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ISDELETED", property = "isdeleted", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DELETEUSERID", property = "deleteuserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DELETETIME", property = "deletetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CUSTOMERID", property = "customerid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FIRSTCONTACTSID", property = "firstcontactsid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ISFIRST", property = "isfirst", jdbcType = JdbcType.DECIMAL) })
	List<TbCrmContacts> selectByExample(TbCrmContactsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@Select({ "select", "CONTACTSID, CREATORUSERID, NAME, POST, DEPARTMENT, SEX, SALTNAME, TELEPHONE, ",
			"EMAIL, QQNO, ADDRESS, ZIPCODE, DESCRIPTION, CREATETIME, UPDATDTIME, ISDELETED, ",
			"DELETEUSERID, DELETETIME, CUSTOMERID, FIRSTCONTACTSID, ISFIRST", "from TB_CRM_CONTACTS",
			"where CONTACTSID = #{contactsid,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "CONTACTSID", property = "contactsid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATORUSERID", property = "creatoruserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "POST", property = "post", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DEPARTMENT", property = "department", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SEX", property = "sex", jdbcType = JdbcType.DECIMAL),
			@Result(column = "SALTNAME", property = "saltname", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TELEPHONE", property = "telephone", jdbcType = JdbcType.VARCHAR),
			@Result(column = "EMAIL", property = "email", jdbcType = JdbcType.VARCHAR),
			@Result(column = "QQNO", property = "qqno", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ADDRESS", property = "address", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ZIPCODE", property = "zipcode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DESCRIPTION", property = "description", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "UPDATDTIME", property = "updatdtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ISDELETED", property = "isdeleted", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DELETEUSERID", property = "deleteuserid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "DELETETIME", property = "deletetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CUSTOMERID", property = "customerid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FIRSTCONTACTSID", property = "firstcontactsid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ISFIRST", property = "isfirst", jdbcType = JdbcType.DECIMAL) })
	TbCrmContacts selectByPrimaryKey(String contactsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@UpdateProvider(type = TbCrmContactsSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TbCrmContacts record, @Param("example") TbCrmContactsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@UpdateProvider(type = TbCrmContactsSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TbCrmContacts record, @Param("example") TbCrmContactsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@UpdateProvider(type = TbCrmContactsSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TbCrmContacts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_CONTACTS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@Update({ "update TB_CRM_CONTACTS", "set CREATORUSERID = #{creatoruserid,jdbcType=VARCHAR},",
			"NAME = #{name,jdbcType=VARCHAR},", "POST = #{post,jdbcType=VARCHAR},",
			"DEPARTMENT = #{department,jdbcType=VARCHAR},", "SEX = #{sex,jdbcType=DECIMAL},",
			"SALTNAME = #{saltname,jdbcType=VARCHAR},", "TELEPHONE = #{telephone,jdbcType=VARCHAR},",
			"EMAIL = #{email,jdbcType=VARCHAR},", "QQNO = #{qqno,jdbcType=VARCHAR},",
			"ADDRESS = #{address,jdbcType=VARCHAR},", "ZIPCODE = #{zipcode,jdbcType=VARCHAR},",
			"DESCRIPTION = #{description,jdbcType=VARCHAR},", "CREATETIME = #{createtime,jdbcType=TIMESTAMP},",
			"UPDATDTIME = #{updatdtime,jdbcType=TIMESTAMP},", "ISDELETED = #{isdeleted,jdbcType=DECIMAL},",
			"DELETEUSERID = #{deleteuserid,jdbcType=VARCHAR},", "DELETETIME = #{deletetime,jdbcType=TIMESTAMP},",
			"CUSTOMERID = #{customerid,jdbcType=VARCHAR},", "FIRSTCONTACTSID = #{firstcontactsid,jdbcType=VARCHAR},",
			"ISFIRST = #{isfirst,jdbcType=DECIMAL}", "where CONTACTSID = #{contactsid,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(TbCrmContacts record);
}