package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbCrmBusinessStatus;
import com.zhidisoft.crm.entity.TbCrmBusinessStatusExample;
import com.zhidisoft.crm.vo.FourVO;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TbCrmBusinessStatusMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@SelectProvider(type = TbCrmBusinessStatusSqlProvider.class, method = "countByExample")
	long countByExample(TbCrmBusinessStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@DeleteProvider(type = TbCrmBusinessStatusSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbCrmBusinessStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@Delete({ "delete from TB_CRM_BUSINESS_STATUS", "where STATUSID = #{statusid,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String statusid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@Insert({ "insert into TB_CRM_BUSINESS_STATUS (STATUSID, NAME, ", "ORDERID, ISEND, ", "DESCRIPTION)",
			"values (#{statusid,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
			"#{orderid,jdbcType=DECIMAL}, #{isend,jdbcType=DECIMAL}, ", "#{description,jdbcType=VARCHAR})" })
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "statusid", before = true, resultType = String.class)
	int insert(TbCrmBusinessStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@InsertProvider(type = TbCrmBusinessStatusSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "statusid", before = true, resultType = String.class)
	int insertSelective(TbCrmBusinessStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@SelectProvider(type = TbCrmBusinessStatusSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "STATUSID", property = "statusid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ORDERID", property = "orderid", jdbcType = JdbcType.DECIMAL),
			@Result(column = "ISEND", property = "isend", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DESCRIPTION", property = "description", jdbcType = JdbcType.VARCHAR) })
	List<TbCrmBusinessStatus> selectByExample(TbCrmBusinessStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@Select({ "select", "STATUSID, NAME, ORDERID, ISEND, DESCRIPTION", "from TB_CRM_BUSINESS_STATUS",
			"where STATUSID = #{statusid,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "STATUSID", property = "statusid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ORDERID", property = "orderid", jdbcType = JdbcType.DECIMAL),
			@Result(column = "ISEND", property = "isend", jdbcType = JdbcType.DECIMAL),
			@Result(column = "DESCRIPTION", property = "description", jdbcType = JdbcType.VARCHAR) })
	TbCrmBusinessStatus selectByPrimaryKey(String statusid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@UpdateProvider(type = TbCrmBusinessStatusSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TbCrmBusinessStatus record,
			@Param("example") TbCrmBusinessStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@UpdateProvider(type = TbCrmBusinessStatusSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TbCrmBusinessStatus record,
			@Param("example") TbCrmBusinessStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@UpdateProvider(type = TbCrmBusinessStatusSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TbCrmBusinessStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_BUSINESS_STATUS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	@Update({ "update TB_CRM_BUSINESS_STATUS", "set NAME = #{name,jdbcType=VARCHAR},",
			"ORDERID = #{orderid,jdbcType=DECIMAL},", "ISEND = #{isend,jdbcType=DECIMAL},",
			"DESCRIPTION = #{description,jdbcType=VARCHAR}", "where STATUSID = #{statusid,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(TbCrmBusinessStatus record);
	
	

}