package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbCrmProductImages;
import com.zhidisoft.crm.entity.TbCrmProductImagesExample.Criteria;
import com.zhidisoft.crm.entity.TbCrmProductImagesExample.Criterion;
import com.zhidisoft.crm.entity.TbCrmProductImagesExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TbCrmProductImagesSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String countByExample(TbCrmProductImagesExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("TB_CRM_PRODUCT_IMAGES");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String deleteByExample(TbCrmProductImagesExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("TB_CRM_PRODUCT_IMAGES");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String insertSelective(TbCrmProductImages record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("TB_CRM_PRODUCT_IMAGES");
        
        if (record.getImagesid() != null) {
            sql.VALUES("IMAGESID", "#{imagesid,jdbcType=VARCHAR}");
        }
        
        if (record.getProductid() != null) {
            sql.VALUES("PRODUCTID", "#{productid,jdbcType=VARCHAR}");
        }
        
        if (record.getIsmain() != null) {
            sql.VALUES("ISMAIN", "#{ismain,jdbcType=DECIMAL}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("NAME", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getSavename() != null) {
            sql.VALUES("SAVENAME", "#{savename,jdbcType=VARCHAR}");
        }
        
        if (record.getImagesize() != null) {
            sql.VALUES("IMAGESIZE", "#{imagesize,jdbcType=VARCHAR}");
        }
        
        if (record.getPath() != null) {
            sql.VALUES("PATH", "#{path,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.VALUES("CREATETIME", "#{createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSortnum() != null) {
            sql.VALUES("SORTNUM", "#{sortnum,jdbcType=DECIMAL}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String selectByExample(TbCrmProductImagesExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("IMAGESID");
        } else {
            sql.SELECT("IMAGESID");
        }
        sql.SELECT("PRODUCTID");
        sql.SELECT("ISMAIN");
        sql.SELECT("NAME");
        sql.SELECT("SAVENAME");
        sql.SELECT("IMAGESIZE");
        sql.SELECT("PATH");
        sql.SELECT("CREATETIME");
        sql.SELECT("SORTNUM");
        sql.FROM("TB_CRM_PRODUCT_IMAGES");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TbCrmProductImages record = (TbCrmProductImages) parameter.get("record");
        TbCrmProductImagesExample example = (TbCrmProductImagesExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("TB_CRM_PRODUCT_IMAGES");
        
        if (record.getImagesid() != null) {
            sql.SET("IMAGESID = #{record.imagesid,jdbcType=VARCHAR}");
        }
        
        if (record.getProductid() != null) {
            sql.SET("PRODUCTID = #{record.productid,jdbcType=VARCHAR}");
        }
        
        if (record.getIsmain() != null) {
            sql.SET("ISMAIN = #{record.ismain,jdbcType=DECIMAL}");
        }
        
        if (record.getName() != null) {
            sql.SET("NAME = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getSavename() != null) {
            sql.SET("SAVENAME = #{record.savename,jdbcType=VARCHAR}");
        }
        
        if (record.getImagesize() != null) {
            sql.SET("IMAGESIZE = #{record.imagesize,jdbcType=VARCHAR}");
        }
        
        if (record.getPath() != null) {
            sql.SET("PATH = #{record.path,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("CREATETIME = #{record.createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSortnum() != null) {
            sql.SET("SORTNUM = #{record.sortnum,jdbcType=DECIMAL}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("TB_CRM_PRODUCT_IMAGES");
        
        sql.SET("IMAGESID = #{record.imagesid,jdbcType=VARCHAR}");
        sql.SET("PRODUCTID = #{record.productid,jdbcType=VARCHAR}");
        sql.SET("ISMAIN = #{record.ismain,jdbcType=DECIMAL}");
        sql.SET("NAME = #{record.name,jdbcType=VARCHAR}");
        sql.SET("SAVENAME = #{record.savename,jdbcType=VARCHAR}");
        sql.SET("IMAGESIZE = #{record.imagesize,jdbcType=VARCHAR}");
        sql.SET("PATH = #{record.path,jdbcType=VARCHAR}");
        sql.SET("CREATETIME = #{record.createtime,jdbcType=TIMESTAMP}");
        sql.SET("SORTNUM = #{record.sortnum,jdbcType=DECIMAL}");
        
        TbCrmProductImagesExample example = (TbCrmProductImagesExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String updateByPrimaryKeySelective(TbCrmProductImages record) {
        SQL sql = new SQL();
        sql.UPDATE("TB_CRM_PRODUCT_IMAGES");
        
        if (record.getProductid() != null) {
            sql.SET("PRODUCTID = #{productid,jdbcType=VARCHAR}");
        }
        
        if (record.getIsmain() != null) {
            sql.SET("ISMAIN = #{ismain,jdbcType=DECIMAL}");
        }
        
        if (record.getName() != null) {
            sql.SET("NAME = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getSavename() != null) {
            sql.SET("SAVENAME = #{savename,jdbcType=VARCHAR}");
        }
        
        if (record.getImagesize() != null) {
            sql.SET("IMAGESIZE = #{imagesize,jdbcType=VARCHAR}");
        }
        
        if (record.getPath() != null) {
            sql.SET("PATH = #{path,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("CREATETIME = #{createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSortnum() != null) {
            sql.SET("SORTNUM = #{sortnum,jdbcType=DECIMAL}");
        }
        
        sql.WHERE("IMAGESID = #{imagesid,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT_IMAGES
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    protected void applyWhere(SQL sql, TbCrmProductImagesExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}