package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbCrmMessage;
import com.zhidisoft.crm.entity.TbCrmMessageExample.Criteria;
import com.zhidisoft.crm.entity.TbCrmMessageExample.Criterion;
import com.zhidisoft.crm.entity.TbCrmMessageExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TbCrmMessageSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public String countByExample(TbCrmMessageExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("TB_CRM_MESSAGE");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public String deleteByExample(TbCrmMessageExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("TB_CRM_MESSAGE");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public String insertSelective(TbCrmMessage record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("TB_CRM_MESSAGE");
		if (record.getMessageid() != null) {
			sql.VALUES("MESSAGEID", "#{messageid,jdbcType=VARCHAR}");
		}
		if (record.getTouserid() != null) {
			sql.VALUES("TOUSERID", "#{touserid,jdbcType=VARCHAR}");
		}
		if (record.getFromuserid() != null) {
			sql.VALUES("FROMUSERID", "#{fromuserid,jdbcType=VARCHAR}");
		}
		if (record.getReadtime() != null) {
			sql.VALUES("READTIME", "#{readtime,jdbcType=TIMESTAMP}");
		}
		if (record.getSendtime() != null) {
			sql.VALUES("SENDTIME", "#{sendtime,jdbcType=TIMESTAMP}");
		}
		if (record.getStatus() != null) {
			sql.VALUES("STATUS", "#{status,jdbcType=DECIMAL}");
		}
		if (record.getContent() != null) {
			sql.VALUES("CONTENT", "#{content,jdbcType=CLOB}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public String selectByExampleWithBLOBs(TbCrmMessageExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("MESSAGEID");
		} else {
			sql.SELECT("MESSAGEID");
		}
		sql.SELECT("TOUSERID");
		sql.SELECT("FROMUSERID");
		sql.SELECT("READTIME");
		sql.SELECT("SENDTIME");
		sql.SELECT("STATUS");
		sql.SELECT("CONTENT");
		sql.FROM("TB_CRM_MESSAGE");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public String selectByExample(TbCrmMessageExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("MESSAGEID");
		} else {
			sql.SELECT("MESSAGEID");
		}
		sql.SELECT("TOUSERID");
		sql.SELECT("FROMUSERID");
		sql.SELECT("READTIME");
		sql.SELECT("SENDTIME");
		sql.SELECT("STATUS");
		sql.FROM("TB_CRM_MESSAGE");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		TbCrmMessage record = (TbCrmMessage) parameter.get("record");
		TbCrmMessageExample example = (TbCrmMessageExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("TB_CRM_MESSAGE");
		if (record.getMessageid() != null) {
			sql.SET("MESSAGEID = #{record.messageid,jdbcType=VARCHAR}");
		}
		if (record.getTouserid() != null) {
			sql.SET("TOUSERID = #{record.touserid,jdbcType=VARCHAR}");
		}
		if (record.getFromuserid() != null) {
			sql.SET("FROMUSERID = #{record.fromuserid,jdbcType=VARCHAR}");
		}
		if (record.getReadtime() != null) {
			sql.SET("READTIME = #{record.readtime,jdbcType=TIMESTAMP}");
		}
		if (record.getSendtime() != null) {
			sql.SET("SENDTIME = #{record.sendtime,jdbcType=TIMESTAMP}");
		}
		if (record.getStatus() != null) {
			sql.SET("STATUS = #{record.status,jdbcType=DECIMAL}");
		}
		if (record.getContent() != null) {
			sql.SET("CONTENT = #{record.content,jdbcType=CLOB}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("TB_CRM_MESSAGE");
		sql.SET("MESSAGEID = #{record.messageid,jdbcType=VARCHAR}");
		sql.SET("TOUSERID = #{record.touserid,jdbcType=VARCHAR}");
		sql.SET("FROMUSERID = #{record.fromuserid,jdbcType=VARCHAR}");
		sql.SET("READTIME = #{record.readtime,jdbcType=TIMESTAMP}");
		sql.SET("SENDTIME = #{record.sendtime,jdbcType=TIMESTAMP}");
		sql.SET("STATUS = #{record.status,jdbcType=DECIMAL}");
		sql.SET("CONTENT = #{record.content,jdbcType=CLOB}");
		TbCrmMessageExample example = (TbCrmMessageExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("TB_CRM_MESSAGE");
		sql.SET("MESSAGEID = #{record.messageid,jdbcType=VARCHAR}");
		sql.SET("TOUSERID = #{record.touserid,jdbcType=VARCHAR}");
		sql.SET("FROMUSERID = #{record.fromuserid,jdbcType=VARCHAR}");
		sql.SET("READTIME = #{record.readtime,jdbcType=TIMESTAMP}");
		sql.SET("SENDTIME = #{record.sendtime,jdbcType=TIMESTAMP}");
		sql.SET("STATUS = #{record.status,jdbcType=DECIMAL}");
		TbCrmMessageExample example = (TbCrmMessageExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public String updateByPrimaryKeySelective(TbCrmMessage record) {
		SQL sql = new SQL();
		sql.UPDATE("TB_CRM_MESSAGE");
		if (record.getTouserid() != null) {
			sql.SET("TOUSERID = #{touserid,jdbcType=VARCHAR}");
		}
		if (record.getFromuserid() != null) {
			sql.SET("FROMUSERID = #{fromuserid,jdbcType=VARCHAR}");
		}
		if (record.getReadtime() != null) {
			sql.SET("READTIME = #{readtime,jdbcType=TIMESTAMP}");
		}
		if (record.getSendtime() != null) {
			sql.SET("SENDTIME = #{sendtime,jdbcType=TIMESTAMP}");
		}
		if (record.getStatus() != null) {
			sql.SET("STATUS = #{status,jdbcType=DECIMAL}");
		}
		if (record.getContent() != null) {
			sql.SET("CONTENT = #{content,jdbcType=CLOB}");
		}
		sql.WHERE("MESSAGEID = #{messageid,jdbcType=VARCHAR}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	protected void applyWhere(SQL sql, TbCrmMessageExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}