package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbSystemRole;
import com.zhidisoft.crm.entity.TbSystemRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface TbSystemRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@SelectProvider(type = TbSystemRoleSqlProvider.class, method = "countByExample")
	long countByExample(TbSystemRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@DeleteProvider(type = TbSystemRoleSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbSystemRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Delete({ "delete from TB_SYSTEM_ROLE", "where ID = #{id,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Insert({ "insert into TB_SYSTEM_ROLE (ID, CREATETIME, ", "ROLENAME, ROLENOTE, ", "SORTNUM, STATUS, ",
			"UPDATETIME, CREATEBY, ", "UPDATEBY)", "values (#{id,jdbcType=VARCHAR}, #{createtime,jdbcType=TIMESTAMP}, ",
			"#{rolename,jdbcType=VARCHAR}, #{rolenote,jdbcType=VARCHAR}, ",
			"#{sortnum,jdbcType=DECIMAL}, #{status,jdbcType=DECIMAL}, ",
			"#{updatetime,jdbcType=TIMESTAMP}, #{createby,jdbcType=VARCHAR}, ", "#{updateby,jdbcType=VARCHAR})" })
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "id", before = true, resultType = String.class)
	int insert(TbSystemRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@InsertProvider(type = TbSystemRoleSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "id", before = true, resultType = String.class)
	int insertSelective(TbSystemRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@SelectProvider(type = TbSystemRoleSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ROLENAME", property = "rolename", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ROLENOTE", property = "rolenote", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SORTNUM", property = "sortnum", jdbcType = JdbcType.DECIMAL),
			@Result(column = "STATUS", property = "status", jdbcType = JdbcType.DECIMAL),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CREATEBY", property = "createby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "UPDATEBY", property = "updateby", jdbcType = JdbcType.VARCHAR) })
	List<TbSystemRole> selectByExampleWithRowbounds(TbSystemRoleExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@SelectProvider(type = TbSystemRoleSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ROLENAME", property = "rolename", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ROLENOTE", property = "rolenote", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SORTNUM", property = "sortnum", jdbcType = JdbcType.DECIMAL),
			@Result(column = "STATUS", property = "status", jdbcType = JdbcType.DECIMAL),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CREATEBY", property = "createby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "UPDATEBY", property = "updateby", jdbcType = JdbcType.VARCHAR) })
	List<TbSystemRole> selectByExample(TbSystemRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Select({ "select", "ID, CREATETIME, ROLENAME, ROLENOTE, SORTNUM, STATUS, UPDATETIME, CREATEBY, UPDATEBY",
			"from TB_SYSTEM_ROLE", "where ID = #{id,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "ROLENAME", property = "rolename", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ROLENOTE", property = "rolenote", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SORTNUM", property = "sortnum", jdbcType = JdbcType.DECIMAL),
			@Result(column = "STATUS", property = "status", jdbcType = JdbcType.DECIMAL),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CREATEBY", property = "createby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "UPDATEBY", property = "updateby", jdbcType = JdbcType.VARCHAR) })
	TbSystemRole selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@UpdateProvider(type = TbSystemRoleSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TbSystemRole record, @Param("example") TbSystemRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@UpdateProvider(type = TbSystemRoleSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TbSystemRole record, @Param("example") TbSystemRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@UpdateProvider(type = TbSystemRoleSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TbSystemRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Update({ "update TB_SYSTEM_ROLE", "set CREATETIME = #{createtime,jdbcType=TIMESTAMP},",
			"ROLENAME = #{rolename,jdbcType=VARCHAR},", "ROLENOTE = #{rolenote,jdbcType=VARCHAR},",
			"SORTNUM = #{sortnum,jdbcType=DECIMAL},", "STATUS = #{status,jdbcType=DECIMAL},",
			"UPDATETIME = #{updatetime,jdbcType=TIMESTAMP},", "CREATEBY = #{createby,jdbcType=VARCHAR},",
			"UPDATEBY = #{updateby,jdbcType=VARCHAR}", "where ID = #{id,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(TbSystemRole record);
	
	@Select({"<script>"
			+ "SELECT * "
			,"FROM (SELECT ROWNUM AS rowno,r.* "
			, " FROM("
			, "select * from tb_system_role "
			," <where>"
			,"   <if test='searchText !=null'>"
					+ " rolename like '%${searchText}%'"
			,"   </if>"
			," </where>"
			, " ) r"
			, " <![CDATA[ where ROWNUM <= #{endIndex} ]]>"
			," ) table_alias"
			, " WHERE table_alias.rowno > ${beginIndex}",
			"</script>"})	
    List<TbSystemRole> selectByPage(@Param("beginIndex")Integer beginIndex,@Param("endIndex")Integer endIndex,@Param("searchText")String searchText);
    
}