package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbSystemUser;
import com.zhidisoft.crm.entity.TbSystemUserExample;
import com.zhidisoft.crm.vo.UserRoleVO;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface TbSystemUserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@SelectProvider(type = TbSystemUserSqlProvider.class, method = "countByExample")
	long countByExample(TbSystemUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@DeleteProvider(type = TbSystemUserSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbSystemUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Delete({ "delete from TB_SYSTEM_USER", "where ID = #{id,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Insert({ "insert into TB_SYSTEM_USER (ID, CREATETIME, ", "EMAIL, PASSWORD, ", "PHONE, SALT, SORTNUM, ",
			"STATUS, UPDATETIME, ", "USERNOTE, USERNAME, ", "CREATEBY, UPDATEBY, ", "ROLE_ID)",
			"values (#{id,jdbcType=VARCHAR}, #{createtime,jdbcType=TIMESTAMP}, ",
			"#{email,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
			"#{phone,jdbcType=VARCHAR}, #{salt,jdbcType=VARCHAR}, #{sortnum,jdbcType=DECIMAL}, ",
			"#{status,jdbcType=DECIMAL}, #{updatetime,jdbcType=TIMESTAMP}, ",
			"#{usernote,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
			"#{createby,jdbcType=VARCHAR}, #{updateby,jdbcType=VARCHAR}, ", "#{roleId,jdbcType=VARCHAR})" })
	// @SelectKey(statement = "select sys_guid() from dual", keyProperty = "id", before = true, resultType = String.class)
	@SelectKey(statement = "select REPLACE(UUID(),'-','')", keyProperty = "id", before = true, resultType = String.class)
	int insert(TbSystemUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@InsertProvider(type = TbSystemUserSqlProvider.class, method = "insertSelective")
	// @SelectKey(statement = "select sys_guid() from dual", keyProperty = "id", before = true, resultType = String.class)
	@SelectKey(statement = "select REPLACE(UUID(),'-','')", keyProperty = "id", before = true, resultType = String.class)
	int insertSelective(TbSystemUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@SelectProvider(type = TbSystemUserSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "EMAIL", property = "email", jdbcType = JdbcType.VARCHAR),
			@Result(column = "PASSWORD", property = "password", jdbcType = JdbcType.VARCHAR),
			@Result(column = "PHONE", property = "phone", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SALT", property = "salt", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SORTNUM", property = "sortnum", jdbcType = JdbcType.DECIMAL),
			@Result(column = "STATUS", property = "status", jdbcType = JdbcType.DECIMAL),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USERNOTE", property = "usernote", jdbcType = JdbcType.VARCHAR),
			@Result(column = "USERNAME", property = "username", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATEBY", property = "createby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "UPDATEBY", property = "updateby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ROLE_ID", property = "roleId", jdbcType = JdbcType.VARCHAR) })
	List<TbSystemUser> selectByExampleWithRowbounds(TbSystemUserExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@SelectProvider(type = TbSystemUserSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "EMAIL", property = "email", jdbcType = JdbcType.VARCHAR),
			@Result(column = "PASSWORD", property = "password", jdbcType = JdbcType.VARCHAR),
			@Result(column = "PHONE", property = "phone", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SALT", property = "salt", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SORTNUM", property = "sortnum", jdbcType = JdbcType.DECIMAL),
			@Result(column = "STATUS", property = "status", jdbcType = JdbcType.DECIMAL),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USERNOTE", property = "usernote", jdbcType = JdbcType.VARCHAR),
			@Result(column = "USERNAME", property = "username", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATEBY", property = "createby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "UPDATEBY", property = "updateby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ROLE_ID", property = "roleId", jdbcType = JdbcType.VARCHAR) })
	List<TbSystemUser> selectByExample(TbSystemUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Select({ "select", "ID, CREATETIME, EMAIL, PASSWORD, PHONE, SALT, SORTNUM, STATUS, UPDATETIME, USERNOTE, ",
			"USERNAME, CREATEBY, UPDATEBY, ROLE_ID", "from TB_SYSTEM_USER", "where ID = #{id,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "EMAIL", property = "email", jdbcType = JdbcType.VARCHAR),
			@Result(column = "PASSWORD", property = "password", jdbcType = JdbcType.VARCHAR),
			@Result(column = "PHONE", property = "phone", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SALT", property = "salt", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SORTNUM", property = "sortnum", jdbcType = JdbcType.DECIMAL),
			@Result(column = "STATUS", property = "status", jdbcType = JdbcType.DECIMAL),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USERNOTE", property = "usernote", jdbcType = JdbcType.VARCHAR),
			@Result(column = "USERNAME", property = "username", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATEBY", property = "createby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "UPDATEBY", property = "updateby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ROLE_ID", property = "roleId", jdbcType = JdbcType.VARCHAR) })
	TbSystemUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@UpdateProvider(type = TbSystemUserSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TbSystemUser record, @Param("example") TbSystemUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@UpdateProvider(type = TbSystemUserSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TbSystemUser record, @Param("example") TbSystemUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@UpdateProvider(type = TbSystemUserSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TbSystemUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_USER
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Update({ "update TB_SYSTEM_USER", "set CREATETIME = #{createtime,jdbcType=TIMESTAMP},",
			"EMAIL = #{email,jdbcType=VARCHAR},", "PASSWORD = #{password,jdbcType=VARCHAR},",
			"PHONE = #{phone,jdbcType=VARCHAR},", "SALT = #{salt,jdbcType=VARCHAR},",
			"SORTNUM = #{sortnum,jdbcType=DECIMAL},", "STATUS = #{status,jdbcType=DECIMAL},",
			"UPDATETIME = #{updatetime,jdbcType=TIMESTAMP},", "USERNOTE = #{usernote,jdbcType=VARCHAR},",
			"USERNAME = #{username,jdbcType=VARCHAR},", "CREATEBY = #{createby,jdbcType=VARCHAR},",
			"UPDATEBY = #{updateby,jdbcType=VARCHAR},", "ROLE_ID = #{roleId,jdbcType=VARCHAR}",
			"where ID = #{id,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(TbSystemUser record);

	/*@Select({"<script>"
			+ "SELECT * "
			,"FROM (SELECT ROWNUM AS rowno,r.* "
			, " FROM("
			, "select * from tb_system_user "
			," <where>"
			,"   <if test='searchText !=null'>"
					+ " username like '%${searchText}%'"
			,"   </if>"
			," </where>"
			, " ) r"
			, " <![CDATA[ where ROWNUM <= #{endIndex} ]]>"
			," ) table_alias"
			, " WHERE table_alias.rowno > ${beginIndex}",
			"</script>"})	
    List<TbSystemUser> selectByPage(@Param("beginIndex")Integer beginIndex,@Param("endIndex")Integer endIndex,@Param("searchText")String searchText);*/
	@Select({"<script>"
			, "select * from tb_system_user "
			," <where>"
			,"   <if test='searchText !=null'>"
					+ " username like '%${searchText}%'"
			,"   </if>"
			," </where>"
			
			," limit #{beginIndex},#{endIndex}"
			,"</script>"})	
    List<TbSystemUser> selectByPage(@Param("beginIndex")Integer beginIndex,@Param("endIndex")Integer endIndex,@Param("searchText")String searchText);
    @Select({
    	"select u.username,r.rolename,u.role_id from Tb_System_User u",
		"left join Tb_System_Role r on u.role_id = r.id",
		"where u.id = #{userId}"
    })
	UserRoleVO selectRoleByUserId(String userId);
    
}