package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbSystemFunction;
import com.zhidisoft.crm.entity.TbSystemFunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface TbSystemFunctionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@SelectProvider(type = TbSystemFunctionSqlProvider.class, method = "countByExample")
	long countByExample(TbSystemFunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@DeleteProvider(type = TbSystemFunctionSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbSystemFunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Delete({ "delete from TB_SYSTEM_FUNCTION", "where ID = #{id,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Insert({ "insert into TB_SYSTEM_FUNCTION (ID, CREATETIME, ", "FUNCCODE, FUNCNAME, ", "FUNCNOTE, FUNCTYPE, ",
			"FUNCURL, ICONCLASS, ", "ICONURL, SORTNUM, ", "STATUS, UPDATETIME, ", "CREATEBY, PARENTID, ", "UPDATEBY)",
			"values (#{id,jdbcType=VARCHAR}, #{createtime,jdbcType=TIMESTAMP}, ",
			"#{funccode,jdbcType=VARCHAR}, #{funcname,jdbcType=VARCHAR}, ",
			"#{funcnote,jdbcType=VARCHAR}, #{functype,jdbcType=DECIMAL}, ",
			"#{funcurl,jdbcType=VARCHAR}, #{iconclass,jdbcType=VARCHAR}, ",
			"#{iconurl,jdbcType=VARCHAR}, #{sortnum,jdbcType=DECIMAL}, ",
			"#{status,jdbcType=DECIMAL}, #{updatetime,jdbcType=TIMESTAMP}, ",
			"#{createby,jdbcType=VARCHAR}, #{parentid,jdbcType=VARCHAR}, ", "#{updateby,jdbcType=VARCHAR})" })
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "id", before = true, resultType = String.class)
	int insert(TbSystemFunction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@InsertProvider(type = TbSystemFunctionSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "select sys_guid() from dual", keyProperty = "id", before = true, resultType = String.class)
	int insertSelective(TbSystemFunction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@SelectProvider(type = TbSystemFunctionSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "FUNCCODE", property = "funccode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FUNCNAME", property = "funcname", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FUNCNOTE", property = "funcnote", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FUNCTYPE", property = "functype", jdbcType = JdbcType.DECIMAL),
			@Result(column = "FUNCURL", property = "funcurl", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ICONCLASS", property = "iconclass", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ICONURL", property = "iconurl", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SORTNUM", property = "sortnum", jdbcType = JdbcType.DECIMAL),
			@Result(column = "STATUS", property = "status", jdbcType = JdbcType.DECIMAL),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CREATEBY", property = "createby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "PARENTID", property = "parentid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "UPDATEBY", property = "updateby", jdbcType = JdbcType.VARCHAR) })
	List<TbSystemFunction> selectByExampleWithRowbounds(TbSystemFunctionExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@SelectProvider(type = TbSystemFunctionSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "FUNCCODE", property = "funccode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FUNCNAME", property = "funcname", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FUNCNOTE", property = "funcnote", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FUNCTYPE", property = "functype", jdbcType = JdbcType.DECIMAL),
			@Result(column = "FUNCURL", property = "funcurl", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ICONCLASS", property = "iconclass", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ICONURL", property = "iconurl", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SORTNUM", property = "sortnum", jdbcType = JdbcType.DECIMAL),
			@Result(column = "STATUS", property = "status", jdbcType = JdbcType.DECIMAL),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CREATEBY", property = "createby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "PARENTID", property = "parentid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "UPDATEBY", property = "updateby", jdbcType = JdbcType.VARCHAR) })
	List<TbSystemFunction> selectByExample(TbSystemFunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Select({ "select", "ID, CREATETIME, FUNCCODE, FUNCNAME, FUNCNOTE, FUNCTYPE, FUNCURL, ICONCLASS, ",
			"ICONURL, SORTNUM, STATUS, UPDATETIME, CREATEBY, PARENTID, UPDATEBY", "from TB_SYSTEM_FUNCTION",
			"where ID = #{id,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CREATETIME", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "FUNCCODE", property = "funccode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FUNCNAME", property = "funcname", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FUNCNOTE", property = "funcnote", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FUNCTYPE", property = "functype", jdbcType = JdbcType.DECIMAL),
			@Result(column = "FUNCURL", property = "funcurl", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ICONCLASS", property = "iconclass", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ICONURL", property = "iconurl", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SORTNUM", property = "sortnum", jdbcType = JdbcType.DECIMAL),
			@Result(column = "STATUS", property = "status", jdbcType = JdbcType.DECIMAL),
			@Result(column = "UPDATETIME", property = "updatetime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "CREATEBY", property = "createby", jdbcType = JdbcType.VARCHAR),
			@Result(column = "PARENTID", property = "parentid", jdbcType = JdbcType.VARCHAR),
			@Result(column = "UPDATEBY", property = "updateby", jdbcType = JdbcType.VARCHAR) })
	TbSystemFunction selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@UpdateProvider(type = TbSystemFunctionSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TbSystemFunction record,
			@Param("example") TbSystemFunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@UpdateProvider(type = TbSystemFunctionSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TbSystemFunction record, @Param("example") TbSystemFunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@UpdateProvider(type = TbSystemFunctionSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TbSystemFunction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_FUNCTION
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	@Update({ "update TB_SYSTEM_FUNCTION", "set CREATETIME = #{createtime,jdbcType=TIMESTAMP},",
			"FUNCCODE = #{funccode,jdbcType=VARCHAR},", "FUNCNAME = #{funcname,jdbcType=VARCHAR},",
			"FUNCNOTE = #{funcnote,jdbcType=VARCHAR},", "FUNCTYPE = #{functype,jdbcType=DECIMAL},",
			"FUNCURL = #{funcurl,jdbcType=VARCHAR},", "ICONCLASS = #{iconclass,jdbcType=VARCHAR},",
			"ICONURL = #{iconurl,jdbcType=VARCHAR},", "SORTNUM = #{sortnum,jdbcType=DECIMAL},",
			"STATUS = #{status,jdbcType=DECIMAL},", "UPDATETIME = #{updatetime,jdbcType=TIMESTAMP},",
			"CREATEBY = #{createby,jdbcType=VARCHAR},", "PARENTID = #{parentid,jdbcType=VARCHAR},",
			"UPDATEBY = #{updateby,jdbcType=VARCHAR}", "where ID = #{id,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(TbSystemFunction record);
	
	@Select({"<script>"
			+ "SELECT * "
			,"FROM (SELECT ROWNUM AS rowno,r.* "
			, " FROM("
			, "select * from tb_system_function "
			," <where>"
			,"   <if test='searchText !=null'>"
					+ " funccode like '%${searchText}%'"
			,"   </if>"
			," </where>"
			, " ) r"
			, " <![CDATA[ where ROWNUM <= #{endIndex} ]]>"
			," ) table_alias"
			, " WHERE table_alias.rowno > ${beginIndex}",
			"</script>"})	
    List<TbSystemFunction> selectByPage(@Param("beginIndex")Integer beginIndex,@Param("endIndex")Integer endIndex,@Param("searchText")String searchText);
	
	@Select({
		"select * from TB_SYSTEM_FUNCTION f",
		"inner join TB_SYSTEM_ROLE_FUNCTION rf on f.id= rf.funcid",
		"inner join TB_SYSTEM_ROLE r on r.id = rf.roleid",
		"inner join TB_SYSTEM_USER u on r.id = u.role_id",
		"where u.username = #{username}"
	})
	List<TbSystemFunction> selectFuncsByUsername(@Param("username")String username);
}