package com.zhidisoft.crm.mapper;

import com.zhidisoft.crm.entity.TbSystemRoleFunctionExample;
import com.zhidisoft.crm.entity.TbSystemRoleFunctionKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface TbSystemRoleFunctionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	@SelectProvider(type = TbSystemRoleFunctionSqlProvider.class, method = "countByExample")
	long countByExample(TbSystemRoleFunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	@DeleteProvider(type = TbSystemRoleFunctionSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TbSystemRoleFunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	@Delete({ "delete from TB_SYSTEM_ROLE_FUNCTION", "where ROLEID = #{roleid,jdbcType=VARCHAR}",
			"and FUNCID = #{funcid,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(TbSystemRoleFunctionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	@Insert({ "insert into TB_SYSTEM_ROLE_FUNCTION (ROLEID, FUNCID)",
			"values (#{roleid,jdbcType=VARCHAR}, #{funcid,jdbcType=VARCHAR})" })
	int insert(TbSystemRoleFunctionKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	@InsertProvider(type = TbSystemRoleFunctionSqlProvider.class, method = "insertSelective")
	int insertSelective(TbSystemRoleFunctionKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	@SelectProvider(type = TbSystemRoleFunctionSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ROLEID", property = "roleid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "FUNCID", property = "funcid", jdbcType = JdbcType.VARCHAR, id = true) })
	List<TbSystemRoleFunctionKey> selectByExampleWithRowbounds(TbSystemRoleFunctionExample example,
			RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	@SelectProvider(type = TbSystemRoleFunctionSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ROLEID", property = "roleid", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "FUNCID", property = "funcid", jdbcType = JdbcType.VARCHAR, id = true) })
	List<TbSystemRoleFunctionKey> selectByExample(TbSystemRoleFunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	@UpdateProvider(type = TbSystemRoleFunctionSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TbSystemRoleFunctionKey record,
			@Param("example") TbSystemRoleFunctionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	@UpdateProvider(type = TbSystemRoleFunctionSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TbSystemRoleFunctionKey record,
			@Param("example") TbSystemRoleFunctionExample example);
}