package com.zhidisoft.crm.entity;

public class TbCrmProductCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_CATEGORY.CATEGORYID
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    private String categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_CATEGORY.PARENTID
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_CATEGORY.NAME
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_CATEGORY.DESCRIPTION
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_CATEGORY.CATEGORYID
     *
     * @return the value of TB_CRM_PRODUCT_CATEGORY.CATEGORYID
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    public String getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_CATEGORY.CATEGORYID
     *
     * @param categoryid the value for TB_CRM_PRODUCT_CATEGORY.CATEGORYID
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    public void setCategoryid(String categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_CATEGORY.PARENTID
     *
     * @return the value of TB_CRM_PRODUCT_CATEGORY.PARENTID
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_CATEGORY.PARENTID
     *
     * @param parentid the value for TB_CRM_PRODUCT_CATEGORY.PARENTID
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_CATEGORY.NAME
     *
     * @return the value of TB_CRM_PRODUCT_CATEGORY.NAME
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_CATEGORY.NAME
     *
     * @param name the value for TB_CRM_PRODUCT_CATEGORY.NAME
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_CATEGORY.DESCRIPTION
     *
     * @return the value of TB_CRM_PRODUCT_CATEGORY.DESCRIPTION
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_CATEGORY.DESCRIPTION
     *
     * @param description the value for TB_CRM_PRODUCT_CATEGORY.DESCRIPTION
     *
     * @mbg.generated Thu Apr 26 09:49:36 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}