package com.zhidisoft.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbCrmMessageExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public TbCrmMessageExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMessageidIsNull() {
			addCriterion("MESSAGEID is null");
			return (Criteria) this;
		}

		public Criteria andMessageidIsNotNull() {
			addCriterion("MESSAGEID is not null");
			return (Criteria) this;
		}

		public Criteria andMessageidEqualTo(String value) {
			addCriterion("MESSAGEID =", value, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidNotEqualTo(String value) {
			addCriterion("MESSAGEID <>", value, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidGreaterThan(String value) {
			addCriterion("MESSAGEID >", value, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidGreaterThanOrEqualTo(String value) {
			addCriterion("MESSAGEID >=", value, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidLessThan(String value) {
			addCriterion("MESSAGEID <", value, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidLessThanOrEqualTo(String value) {
			addCriterion("MESSAGEID <=", value, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidLike(String value) {
			addCriterion("MESSAGEID like", value, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidNotLike(String value) {
			addCriterion("MESSAGEID not like", value, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidIn(List<String> values) {
			addCriterion("MESSAGEID in", values, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidNotIn(List<String> values) {
			addCriterion("MESSAGEID not in", values, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidBetween(String value1, String value2) {
			addCriterion("MESSAGEID between", value1, value2, "messageid");
			return (Criteria) this;
		}

		public Criteria andMessageidNotBetween(String value1, String value2) {
			addCriterion("MESSAGEID not between", value1, value2, "messageid");
			return (Criteria) this;
		}

		public Criteria andTouseridIsNull() {
			addCriterion("TOUSERID is null");
			return (Criteria) this;
		}

		public Criteria andTouseridIsNotNull() {
			addCriterion("TOUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andTouseridEqualTo(String value) {
			addCriterion("TOUSERID =", value, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridNotEqualTo(String value) {
			addCriterion("TOUSERID <>", value, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridGreaterThan(String value) {
			addCriterion("TOUSERID >", value, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridGreaterThanOrEqualTo(String value) {
			addCriterion("TOUSERID >=", value, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridLessThan(String value) {
			addCriterion("TOUSERID <", value, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridLessThanOrEqualTo(String value) {
			addCriterion("TOUSERID <=", value, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridLike(String value) {
			addCriterion("TOUSERID like", value, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridNotLike(String value) {
			addCriterion("TOUSERID not like", value, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridIn(List<String> values) {
			addCriterion("TOUSERID in", values, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridNotIn(List<String> values) {
			addCriterion("TOUSERID not in", values, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridBetween(String value1, String value2) {
			addCriterion("TOUSERID between", value1, value2, "touserid");
			return (Criteria) this;
		}

		public Criteria andTouseridNotBetween(String value1, String value2) {
			addCriterion("TOUSERID not between", value1, value2, "touserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridIsNull() {
			addCriterion("FROMUSERID is null");
			return (Criteria) this;
		}

		public Criteria andFromuseridIsNotNull() {
			addCriterion("FROMUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andFromuseridEqualTo(String value) {
			addCriterion("FROMUSERID =", value, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridNotEqualTo(String value) {
			addCriterion("FROMUSERID <>", value, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridGreaterThan(String value) {
			addCriterion("FROMUSERID >", value, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridGreaterThanOrEqualTo(String value) {
			addCriterion("FROMUSERID >=", value, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridLessThan(String value) {
			addCriterion("FROMUSERID <", value, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridLessThanOrEqualTo(String value) {
			addCriterion("FROMUSERID <=", value, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridLike(String value) {
			addCriterion("FROMUSERID like", value, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridNotLike(String value) {
			addCriterion("FROMUSERID not like", value, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridIn(List<String> values) {
			addCriterion("FROMUSERID in", values, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridNotIn(List<String> values) {
			addCriterion("FROMUSERID not in", values, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridBetween(String value1, String value2) {
			addCriterion("FROMUSERID between", value1, value2, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andFromuseridNotBetween(String value1, String value2) {
			addCriterion("FROMUSERID not between", value1, value2, "fromuserid");
			return (Criteria) this;
		}

		public Criteria andReadtimeIsNull() {
			addCriterion("READTIME is null");
			return (Criteria) this;
		}

		public Criteria andReadtimeIsNotNull() {
			addCriterion("READTIME is not null");
			return (Criteria) this;
		}

		public Criteria andReadtimeEqualTo(Date value) {
			addCriterion("READTIME =", value, "readtime");
			return (Criteria) this;
		}

		public Criteria andReadtimeNotEqualTo(Date value) {
			addCriterion("READTIME <>", value, "readtime");
			return (Criteria) this;
		}

		public Criteria andReadtimeGreaterThan(Date value) {
			addCriterion("READTIME >", value, "readtime");
			return (Criteria) this;
		}

		public Criteria andReadtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("READTIME >=", value, "readtime");
			return (Criteria) this;
		}

		public Criteria andReadtimeLessThan(Date value) {
			addCriterion("READTIME <", value, "readtime");
			return (Criteria) this;
		}

		public Criteria andReadtimeLessThanOrEqualTo(Date value) {
			addCriterion("READTIME <=", value, "readtime");
			return (Criteria) this;
		}

		public Criteria andReadtimeIn(List<Date> values) {
			addCriterion("READTIME in", values, "readtime");
			return (Criteria) this;
		}

		public Criteria andReadtimeNotIn(List<Date> values) {
			addCriterion("READTIME not in", values, "readtime");
			return (Criteria) this;
		}

		public Criteria andReadtimeBetween(Date value1, Date value2) {
			addCriterion("READTIME between", value1, value2, "readtime");
			return (Criteria) this;
		}

		public Criteria andReadtimeNotBetween(Date value1, Date value2) {
			addCriterion("READTIME not between", value1, value2, "readtime");
			return (Criteria) this;
		}

		public Criteria andSendtimeIsNull() {
			addCriterion("SENDTIME is null");
			return (Criteria) this;
		}

		public Criteria andSendtimeIsNotNull() {
			addCriterion("SENDTIME is not null");
			return (Criteria) this;
		}

		public Criteria andSendtimeEqualTo(Date value) {
			addCriterion("SENDTIME =", value, "sendtime");
			return (Criteria) this;
		}

		public Criteria andSendtimeNotEqualTo(Date value) {
			addCriterion("SENDTIME <>", value, "sendtime");
			return (Criteria) this;
		}

		public Criteria andSendtimeGreaterThan(Date value) {
			addCriterion("SENDTIME >", value, "sendtime");
			return (Criteria) this;
		}

		public Criteria andSendtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("SENDTIME >=", value, "sendtime");
			return (Criteria) this;
		}

		public Criteria andSendtimeLessThan(Date value) {
			addCriterion("SENDTIME <", value, "sendtime");
			return (Criteria) this;
		}

		public Criteria andSendtimeLessThanOrEqualTo(Date value) {
			addCriterion("SENDTIME <=", value, "sendtime");
			return (Criteria) this;
		}

		public Criteria andSendtimeIn(List<Date> values) {
			addCriterion("SENDTIME in", values, "sendtime");
			return (Criteria) this;
		}

		public Criteria andSendtimeNotIn(List<Date> values) {
			addCriterion("SENDTIME not in", values, "sendtime");
			return (Criteria) this;
		}

		public Criteria andSendtimeBetween(Date value1, Date value2) {
			addCriterion("SENDTIME between", value1, value2, "sendtime");
			return (Criteria) this;
		}

		public Criteria andSendtimeNotBetween(Date value1, Date value2) {
			addCriterion("SENDTIME not between", value1, value2, "sendtime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_CRM_MESSAGE
	 * @mbg.generated  Tue Apr 24 11:15:01 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CRM_MESSAGE
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 24 11:15:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}