package com.zhidisoft.crm.entity;

import java.util.Date;

public class TbCrmTask {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.TASKID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private String taskid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.OWNERUSERID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private String owneruserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.ABOUT_USER
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private String aboutUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.SUBJECT
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.DUEDATE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private Date duedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.STATUS
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.PRIORITY
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private String priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.SENDEMAIL
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private String sendemail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.CREATORUSERID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private String creatoruserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.CREATEDATE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.UPDTADATE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private Date updtadate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.ISCLOSE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private Short isclose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.ISDELETED
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private Short isdeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.DELETEUSERID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private String deleteuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.DELETETIME
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private Date deletetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_TASK.DESCRIPTION
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	private byte[] description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.TASKID
	 * @return  the value of TB_CRM_TASK.TASKID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public String getTaskid() {
		return taskid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.TASKID
	 * @param taskid  the value for TB_CRM_TASK.TASKID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setTaskid(String taskid) {
		this.taskid = taskid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.OWNERUSERID
	 * @return  the value of TB_CRM_TASK.OWNERUSERID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public String getOwneruserid() {
		return owneruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.OWNERUSERID
	 * @param owneruserid  the value for TB_CRM_TASK.OWNERUSERID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setOwneruserid(String owneruserid) {
		this.owneruserid = owneruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.ABOUT_USER
	 * @return  the value of TB_CRM_TASK.ABOUT_USER
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public String getAboutUser() {
		return aboutUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.ABOUT_USER
	 * @param aboutUser  the value for TB_CRM_TASK.ABOUT_USER
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setAboutUser(String aboutUser) {
		this.aboutUser = aboutUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.SUBJECT
	 * @return  the value of TB_CRM_TASK.SUBJECT
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.SUBJECT
	 * @param subject  the value for TB_CRM_TASK.SUBJECT
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.DUEDATE
	 * @return  the value of TB_CRM_TASK.DUEDATE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public Date getDuedate() {
		return duedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.DUEDATE
	 * @param duedate  the value for TB_CRM_TASK.DUEDATE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.STATUS
	 * @return  the value of TB_CRM_TASK.STATUS
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.STATUS
	 * @param status  the value for TB_CRM_TASK.STATUS
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.PRIORITY
	 * @return  the value of TB_CRM_TASK.PRIORITY
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public String getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.PRIORITY
	 * @param priority  the value for TB_CRM_TASK.PRIORITY
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setPriority(String priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.SENDEMAIL
	 * @return  the value of TB_CRM_TASK.SENDEMAIL
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public String getSendemail() {
		return sendemail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.SENDEMAIL
	 * @param sendemail  the value for TB_CRM_TASK.SENDEMAIL
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setSendemail(String sendemail) {
		this.sendemail = sendemail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.CREATORUSERID
	 * @return  the value of TB_CRM_TASK.CREATORUSERID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public String getCreatoruserid() {
		return creatoruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.CREATORUSERID
	 * @param creatoruserid  the value for TB_CRM_TASK.CREATORUSERID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setCreatoruserid(String creatoruserid) {
		this.creatoruserid = creatoruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.CREATEDATE
	 * @return  the value of TB_CRM_TASK.CREATEDATE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.CREATEDATE
	 * @param createdate  the value for TB_CRM_TASK.CREATEDATE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.UPDTADATE
	 * @return  the value of TB_CRM_TASK.UPDTADATE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public Date getUpdtadate() {
		return updtadate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.UPDTADATE
	 * @param updtadate  the value for TB_CRM_TASK.UPDTADATE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setUpdtadate(Date updtadate) {
		this.updtadate = updtadate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.ISCLOSE
	 * @return  the value of TB_CRM_TASK.ISCLOSE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public Short getIsclose() {
		return isclose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.ISCLOSE
	 * @param isclose  the value for TB_CRM_TASK.ISCLOSE
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setIsclose(Short isclose) {
		this.isclose = isclose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.ISDELETED
	 * @return  the value of TB_CRM_TASK.ISDELETED
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public Short getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.ISDELETED
	 * @param isdeleted  the value for TB_CRM_TASK.ISDELETED
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setIsdeleted(Short isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.DELETEUSERID
	 * @return  the value of TB_CRM_TASK.DELETEUSERID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public String getDeleteuserid() {
		return deleteuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.DELETEUSERID
	 * @param deleteuserid  the value for TB_CRM_TASK.DELETEUSERID
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setDeleteuserid(String deleteuserid) {
		this.deleteuserid = deleteuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.DELETETIME
	 * @return  the value of TB_CRM_TASK.DELETETIME
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public Date getDeletetime() {
		return deletetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.DELETETIME
	 * @param deletetime  the value for TB_CRM_TASK.DELETETIME
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setDeletetime(Date deletetime) {
		this.deletetime = deletetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_TASK.DESCRIPTION
	 * @return  the value of TB_CRM_TASK.DESCRIPTION
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public byte[] getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_TASK.DESCRIPTION
	 * @param description  the value for TB_CRM_TASK.DESCRIPTION
	 * @mbg.generated  Tue Apr 24 11:03:32 CST 2018
	 */
	public void setDescription(byte[] description) {
		this.description = description;
	}
}