package com.zhidisoft.crm.entity;

import java.math.BigDecimal;
import java.util.Date;
/**
 * 产品表
 * @author ykk
 *
 */
public class TbCrmProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.PRODUCTID
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.CATEGORYID
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private String categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.NAME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.CREATORUSERID
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private String creatoruserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.COSTPRICE
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private BigDecimal costprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.SUGGESTEDPRICE
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private BigDecimal suggestedprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.DEVELOPMENTTEAM
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private String developmentteam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.DEVELOPMENTTIME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private Date developmenttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.LINK
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.CREATETIME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.UPDATETIME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT.DESCRIPTION
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.PRODUCTID
     *
     * @return the value of TB_CRM_PRODUCT.PRODUCTID
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.PRODUCTID
     *
     * @param productid the value for TB_CRM_PRODUCT.PRODUCTID
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.CATEGORYID
     *
     * @return the value of TB_CRM_PRODUCT.CATEGORYID
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public String getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.CATEGORYID
     *
     * @param categoryid the value for TB_CRM_PRODUCT.CATEGORYID
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setCategoryid(String categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.NAME
     *
     * @return the value of TB_CRM_PRODUCT.NAME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.NAME
     *
     * @param name the value for TB_CRM_PRODUCT.NAME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.CREATORUSERID
     *
     * @return the value of TB_CRM_PRODUCT.CREATORUSERID
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public String getCreatoruserid() {
        return creatoruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.CREATORUSERID
     *
     * @param creatoruserid the value for TB_CRM_PRODUCT.CREATORUSERID
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setCreatoruserid(String creatoruserid) {
        this.creatoruserid = creatoruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.COSTPRICE
     *
     * @return the value of TB_CRM_PRODUCT.COSTPRICE
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public BigDecimal getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.COSTPRICE
     *
     * @param costprice the value for TB_CRM_PRODUCT.COSTPRICE
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setCostprice(BigDecimal costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.SUGGESTEDPRICE
     *
     * @return the value of TB_CRM_PRODUCT.SUGGESTEDPRICE
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public BigDecimal getSuggestedprice() {
        return suggestedprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.SUGGESTEDPRICE
     *
     * @param suggestedprice the value for TB_CRM_PRODUCT.SUGGESTEDPRICE
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setSuggestedprice(BigDecimal suggestedprice) {
        this.suggestedprice = suggestedprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.DEVELOPMENTTEAM
     *
     * @return the value of TB_CRM_PRODUCT.DEVELOPMENTTEAM
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public String getDevelopmentteam() {
        return developmentteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.DEVELOPMENTTEAM
     *
     * @param developmentteam the value for TB_CRM_PRODUCT.DEVELOPMENTTEAM
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setDevelopmentteam(String developmentteam) {
        this.developmentteam = developmentteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.DEVELOPMENTTIME
     *
     * @return the value of TB_CRM_PRODUCT.DEVELOPMENTTIME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public Date getDevelopmenttime() {
        return developmenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.DEVELOPMENTTIME
     *
     * @param developmenttime the value for TB_CRM_PRODUCT.DEVELOPMENTTIME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setDevelopmenttime(Date developmenttime) {
        this.developmenttime = developmenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.LINK
     *
     * @return the value of TB_CRM_PRODUCT.LINK
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.LINK
     *
     * @param link the value for TB_CRM_PRODUCT.LINK
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.CREATETIME
     *
     * @return the value of TB_CRM_PRODUCT.CREATETIME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.CREATETIME
     *
     * @param createtime the value for TB_CRM_PRODUCT.CREATETIME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.UPDATETIME
     *
     * @return the value of TB_CRM_PRODUCT.UPDATETIME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.UPDATETIME
     *
     * @param updatetime the value for TB_CRM_PRODUCT.UPDATETIME
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT.DESCRIPTION
     *
     * @return the value of TB_CRM_PRODUCT.DESCRIPTION
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT.DESCRIPTION
     *
     * @param description the value for TB_CRM_PRODUCT.DESCRIPTION
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}