package com.zhidisoft.crm.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbCrmProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public TbCrmProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductidIsNull() {
            addCriterion("PRODUCTID is null");
            return (Criteria) this;
        }

        public Criteria andProductidIsNotNull() {
            addCriterion("PRODUCTID is not null");
            return (Criteria) this;
        }

        public Criteria andProductidEqualTo(String value) {
            addCriterion("PRODUCTID =", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotEqualTo(String value) {
            addCriterion("PRODUCTID <>", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThan(String value) {
            addCriterion("PRODUCTID >", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCTID >=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThan(String value) {
            addCriterion("PRODUCTID <", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThanOrEqualTo(String value) {
            addCriterion("PRODUCTID <=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLike(String value) {
            addCriterion("PRODUCTID like", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotLike(String value) {
            addCriterion("PRODUCTID not like", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidIn(List<String> values) {
            addCriterion("PRODUCTID in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotIn(List<String> values) {
            addCriterion("PRODUCTID not in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidBetween(String value1, String value2) {
            addCriterion("PRODUCTID between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotBetween(String value1, String value2) {
            addCriterion("PRODUCTID not between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andCategoryidIsNull() {
            addCriterion("CATEGORYID is null");
            return (Criteria) this;
        }

        public Criteria andCategoryidIsNotNull() {
            addCriterion("CATEGORYID is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryidEqualTo(String value) {
            addCriterion("CATEGORYID =", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidNotEqualTo(String value) {
            addCriterion("CATEGORYID <>", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidGreaterThan(String value) {
            addCriterion("CATEGORYID >", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORYID >=", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidLessThan(String value) {
            addCriterion("CATEGORYID <", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidLessThanOrEqualTo(String value) {
            addCriterion("CATEGORYID <=", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidLike(String value) {
            addCriterion("CATEGORYID like", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidNotLike(String value) {
            addCriterion("CATEGORYID not like", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidIn(List<String> values) {
            addCriterion("CATEGORYID in", values, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidNotIn(List<String> values) {
            addCriterion("CATEGORYID not in", values, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidBetween(String value1, String value2) {
            addCriterion("CATEGORYID between", value1, value2, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidNotBetween(String value1, String value2) {
            addCriterion("CATEGORYID not between", value1, value2, "categoryid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridIsNull() {
            addCriterion("CREATORUSERID is null");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridIsNotNull() {
            addCriterion("CREATORUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridEqualTo(String value) {
            addCriterion("CREATORUSERID =", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridNotEqualTo(String value) {
            addCriterion("CREATORUSERID <>", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridGreaterThan(String value) {
            addCriterion("CREATORUSERID >", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridGreaterThanOrEqualTo(String value) {
            addCriterion("CREATORUSERID >=", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridLessThan(String value) {
            addCriterion("CREATORUSERID <", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridLessThanOrEqualTo(String value) {
            addCriterion("CREATORUSERID <=", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridLike(String value) {
            addCriterion("CREATORUSERID like", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridNotLike(String value) {
            addCriterion("CREATORUSERID not like", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridIn(List<String> values) {
            addCriterion("CREATORUSERID in", values, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridNotIn(List<String> values) {
            addCriterion("CREATORUSERID not in", values, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridBetween(String value1, String value2) {
            addCriterion("CREATORUSERID between", value1, value2, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridNotBetween(String value1, String value2) {
            addCriterion("CREATORUSERID not between", value1, value2, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCostpriceIsNull() {
            addCriterion("COSTPRICE is null");
            return (Criteria) this;
        }

        public Criteria andCostpriceIsNotNull() {
            addCriterion("COSTPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andCostpriceEqualTo(BigDecimal value) {
            addCriterion("COSTPRICE =", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotEqualTo(BigDecimal value) {
            addCriterion("COSTPRICE <>", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceGreaterThan(BigDecimal value) {
            addCriterion("COSTPRICE >", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COSTPRICE >=", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceLessThan(BigDecimal value) {
            addCriterion("COSTPRICE <", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COSTPRICE <=", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceIn(List<BigDecimal> values) {
            addCriterion("COSTPRICE in", values, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotIn(List<BigDecimal> values) {
            addCriterion("COSTPRICE not in", values, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COSTPRICE between", value1, value2, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COSTPRICE not between", value1, value2, "costprice");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceIsNull() {
            addCriterion("SUGGESTEDPRICE is null");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceIsNotNull() {
            addCriterion("SUGGESTEDPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceEqualTo(BigDecimal value) {
            addCriterion("SUGGESTEDPRICE =", value, "suggestedprice");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceNotEqualTo(BigDecimal value) {
            addCriterion("SUGGESTEDPRICE <>", value, "suggestedprice");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceGreaterThan(BigDecimal value) {
            addCriterion("SUGGESTEDPRICE >", value, "suggestedprice");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUGGESTEDPRICE >=", value, "suggestedprice");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceLessThan(BigDecimal value) {
            addCriterion("SUGGESTEDPRICE <", value, "suggestedprice");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUGGESTEDPRICE <=", value, "suggestedprice");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceIn(List<BigDecimal> values) {
            addCriterion("SUGGESTEDPRICE in", values, "suggestedprice");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceNotIn(List<BigDecimal> values) {
            addCriterion("SUGGESTEDPRICE not in", values, "suggestedprice");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUGGESTEDPRICE between", value1, value2, "suggestedprice");
            return (Criteria) this;
        }

        public Criteria andSuggestedpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUGGESTEDPRICE not between", value1, value2, "suggestedprice");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamIsNull() {
            addCriterion("DEVELOPMENTTEAM is null");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamIsNotNull() {
            addCriterion("DEVELOPMENTTEAM is not null");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamEqualTo(String value) {
            addCriterion("DEVELOPMENTTEAM =", value, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamNotEqualTo(String value) {
            addCriterion("DEVELOPMENTTEAM <>", value, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamGreaterThan(String value) {
            addCriterion("DEVELOPMENTTEAM >", value, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamGreaterThanOrEqualTo(String value) {
            addCriterion("DEVELOPMENTTEAM >=", value, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamLessThan(String value) {
            addCriterion("DEVELOPMENTTEAM <", value, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamLessThanOrEqualTo(String value) {
            addCriterion("DEVELOPMENTTEAM <=", value, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamLike(String value) {
            addCriterion("DEVELOPMENTTEAM like", value, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamNotLike(String value) {
            addCriterion("DEVELOPMENTTEAM not like", value, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamIn(List<String> values) {
            addCriterion("DEVELOPMENTTEAM in", values, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamNotIn(List<String> values) {
            addCriterion("DEVELOPMENTTEAM not in", values, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamBetween(String value1, String value2) {
            addCriterion("DEVELOPMENTTEAM between", value1, value2, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmentteamNotBetween(String value1, String value2) {
            addCriterion("DEVELOPMENTTEAM not between", value1, value2, "developmentteam");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeIsNull() {
            addCriterion("DEVELOPMENTTIME is null");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeIsNotNull() {
            addCriterion("DEVELOPMENTTIME is not null");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeEqualTo(Date value) {
            addCriterion("DEVELOPMENTTIME =", value, "developmenttime");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeNotEqualTo(Date value) {
            addCriterion("DEVELOPMENTTIME <>", value, "developmenttime");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeGreaterThan(Date value) {
            addCriterion("DEVELOPMENTTIME >", value, "developmenttime");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DEVELOPMENTTIME >=", value, "developmenttime");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeLessThan(Date value) {
            addCriterion("DEVELOPMENTTIME <", value, "developmenttime");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeLessThanOrEqualTo(Date value) {
            addCriterion("DEVELOPMENTTIME <=", value, "developmenttime");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeIn(List<Date> values) {
            addCriterion("DEVELOPMENTTIME in", values, "developmenttime");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeNotIn(List<Date> values) {
            addCriterion("DEVELOPMENTTIME not in", values, "developmenttime");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeBetween(Date value1, Date value2) {
            addCriterion("DEVELOPMENTTIME between", value1, value2, "developmenttime");
            return (Criteria) this;
        }

        public Criteria andDevelopmenttimeNotBetween(Date value1, Date value2) {
            addCriterion("DEVELOPMENTTIME not between", value1, value2, "developmenttime");
            return (Criteria) this;
        }

        public Criteria andLinkIsNull() {
            addCriterion("LINK is null");
            return (Criteria) this;
        }

        public Criteria andLinkIsNotNull() {
            addCriterion("LINK is not null");
            return (Criteria) this;
        }

        public Criteria andLinkEqualTo(String value) {
            addCriterion("LINK =", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotEqualTo(String value) {
            addCriterion("LINK <>", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkGreaterThan(String value) {
            addCriterion("LINK >", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkGreaterThanOrEqualTo(String value) {
            addCriterion("LINK >=", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkLessThan(String value) {
            addCriterion("LINK <", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkLessThanOrEqualTo(String value) {
            addCriterion("LINK <=", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkLike(String value) {
            addCriterion("LINK like", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotLike(String value) {
            addCriterion("LINK not like", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkIn(List<String> values) {
            addCriterion("LINK in", values, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotIn(List<String> values) {
            addCriterion("LINK not in", values, "link");
            return (Criteria) this;
        }

        public Criteria andLinkBetween(String value1, String value2) {
            addCriterion("LINK between", value1, value2, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotBetween(String value1, String value2) {
            addCriterion("LINK not between", value1, value2, "link");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CREATETIME =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CREATETIME >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CREATETIME <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CREATETIME in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("UPDATETIME =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("UPDATETIME <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("UPDATETIME >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("UPDATETIME <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("UPDATETIME in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("UPDATETIME not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 24 16:34:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CRM_PRODUCT
     *
     * @mbg.generated Tue Apr 24 16:34:32 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}