package com.zhidisoft.crm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TbCrmBusiness {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.BUSINESSID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String businessid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.NAME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.ORIGIN
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String origin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.TYPE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.ESTIMATEPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private Long estimateprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.CUSTOMERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String customerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.CREATORUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String creatoruserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.OWNERUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String owneruserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.GAINRATE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private Short gainrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.TOTALAMOUNT
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private Long totalamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.SUBTOTALVAL
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private BigDecimal subtotalval;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.DISCOUNTPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private BigDecimal discountprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.SALESPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private BigDecimal salesprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.DUEDATE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private Date duedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.CREATETIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.UPDATETIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.UPDATEUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String updateuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.STATUSID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String statusid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.TOTALPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private BigDecimal totalprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.NEXTSTEP
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String nextstep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.NEXTSTEPTIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private Date nextsteptime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.ISDELETED
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private Short isdeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.DELETEUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String deleteuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.DELETETIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private Date deletetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.CONTACTSID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String contactsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.CONTRACTADDRESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String contractaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_BUSINESS.DESCRIPTION
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.BUSINESSID
	 * @return  the value of TB_CRM_BUSINESS.BUSINESSID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getBusinessid() {
		return businessid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.BUSINESSID
	 * @param businessid  the value for TB_CRM_BUSINESS.BUSINESSID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setBusinessid(String businessid) {
		this.businessid = businessid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.NAME
	 * @return  the value of TB_CRM_BUSINESS.NAME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.NAME
	 * @param name  the value for TB_CRM_BUSINESS.NAME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.ORIGIN
	 * @return  the value of TB_CRM_BUSINESS.ORIGIN
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getOrigin() {
		return origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.ORIGIN
	 * @param origin  the value for TB_CRM_BUSINESS.ORIGIN
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setOrigin(String origin) {
		this.origin = origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.TYPE
	 * @return  the value of TB_CRM_BUSINESS.TYPE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.TYPE
	 * @param type  the value for TB_CRM_BUSINESS.TYPE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.ESTIMATEPRICE
	 * @return  the value of TB_CRM_BUSINESS.ESTIMATEPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public Long getEstimateprice() {
		return estimateprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.ESTIMATEPRICE
	 * @param estimateprice  the value for TB_CRM_BUSINESS.ESTIMATEPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setEstimateprice(Long estimateprice) {
		this.estimateprice = estimateprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.CUSTOMERID
	 * @return  the value of TB_CRM_BUSINESS.CUSTOMERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.CUSTOMERID
	 * @param customerid  the value for TB_CRM_BUSINESS.CUSTOMERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.CREATORUSERID
	 * @return  the value of TB_CRM_BUSINESS.CREATORUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getCreatoruserid() {
		return creatoruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.CREATORUSERID
	 * @param creatoruserid  the value for TB_CRM_BUSINESS.CREATORUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setCreatoruserid(String creatoruserid) {
		this.creatoruserid = creatoruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.OWNERUSERID
	 * @return  the value of TB_CRM_BUSINESS.OWNERUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getOwneruserid() {
		return owneruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.OWNERUSERID
	 * @param owneruserid  the value for TB_CRM_BUSINESS.OWNERUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setOwneruserid(String owneruserid) {
		this.owneruserid = owneruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.GAINRATE
	 * @return  the value of TB_CRM_BUSINESS.GAINRATE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public Short getGainrate() {
		return gainrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.GAINRATE
	 * @param gainrate  the value for TB_CRM_BUSINESS.GAINRATE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setGainrate(Short gainrate) {
		this.gainrate = gainrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.TOTALAMOUNT
	 * @return  the value of TB_CRM_BUSINESS.TOTALAMOUNT
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public Long getTotalamount() {
		return totalamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.TOTALAMOUNT
	 * @param totalamount  the value for TB_CRM_BUSINESS.TOTALAMOUNT
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setTotalamount(Long totalamount) {
		this.totalamount = totalamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.SUBTOTALVAL
	 * @return  the value of TB_CRM_BUSINESS.SUBTOTALVAL
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public BigDecimal getSubtotalval() {
		return subtotalval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.SUBTOTALVAL
	 * @param subtotalval  the value for TB_CRM_BUSINESS.SUBTOTALVAL
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setSubtotalval(BigDecimal subtotalval) {
		this.subtotalval = subtotalval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.DISCOUNTPRICE
	 * @return  the value of TB_CRM_BUSINESS.DISCOUNTPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public BigDecimal getDiscountprice() {
		return discountprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.DISCOUNTPRICE
	 * @param discountprice  the value for TB_CRM_BUSINESS.DISCOUNTPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setDiscountprice(BigDecimal discountprice) {
		this.discountprice = discountprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.SALESPRICE
	 * @return  the value of TB_CRM_BUSINESS.SALESPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public BigDecimal getSalesprice() {
		return salesprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.SALESPRICE
	 * @param salesprice  the value for TB_CRM_BUSINESS.SALESPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setSalesprice(BigDecimal salesprice) {
		this.salesprice = salesprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.DUEDATE
	 * @return  the value of TB_CRM_BUSINESS.DUEDATE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public Date getDuedate() {
		return duedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.DUEDATE
	 * @param duedate  the value for TB_CRM_BUSINESS.DUEDATE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.CREATETIME
	 * @return  the value of TB_CRM_BUSINESS.CREATETIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.CREATETIME
	 * @param createtime  the value for TB_CRM_BUSINESS.CREATETIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.UPDATETIME
	 * @return  the value of TB_CRM_BUSINESS.UPDATETIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.UPDATETIME
	 * @param updatetime  the value for TB_CRM_BUSINESS.UPDATETIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.UPDATEUSERID
	 * @return  the value of TB_CRM_BUSINESS.UPDATEUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getUpdateuserid() {
		return updateuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.UPDATEUSERID
	 * @param updateuserid  the value for TB_CRM_BUSINESS.UPDATEUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setUpdateuserid(String updateuserid) {
		this.updateuserid = updateuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.STATUSID
	 * @return  the value of TB_CRM_BUSINESS.STATUSID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getStatusid() {
		return statusid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.STATUSID
	 * @param statusid  the value for TB_CRM_BUSINESS.STATUSID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setStatusid(String statusid) {
		this.statusid = statusid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.TOTALPRICE
	 * @return  the value of TB_CRM_BUSINESS.TOTALPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public BigDecimal getTotalprice() {
		return totalprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.TOTALPRICE
	 * @param totalprice  the value for TB_CRM_BUSINESS.TOTALPRICE
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setTotalprice(BigDecimal totalprice) {
		this.totalprice = totalprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.NEXTSTEP
	 * @return  the value of TB_CRM_BUSINESS.NEXTSTEP
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getNextstep() {
		return nextstep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.NEXTSTEP
	 * @param nextstep  the value for TB_CRM_BUSINESS.NEXTSTEP
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setNextstep(String nextstep) {
		this.nextstep = nextstep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.NEXTSTEPTIME
	 * @return  the value of TB_CRM_BUSINESS.NEXTSTEPTIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public Date getNextsteptime() {
		return nextsteptime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.NEXTSTEPTIME
	 * @param nextsteptime  the value for TB_CRM_BUSINESS.NEXTSTEPTIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setNextsteptime(Date nextsteptime) {
		this.nextsteptime = nextsteptime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.ISDELETED
	 * @return  the value of TB_CRM_BUSINESS.ISDELETED
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public Short getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.ISDELETED
	 * @param isdeleted  the value for TB_CRM_BUSINESS.ISDELETED
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setIsdeleted(Short isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.DELETEUSERID
	 * @return  the value of TB_CRM_BUSINESS.DELETEUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getDeleteuserid() {
		return deleteuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.DELETEUSERID
	 * @param deleteuserid  the value for TB_CRM_BUSINESS.DELETEUSERID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setDeleteuserid(String deleteuserid) {
		this.deleteuserid = deleteuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.DELETETIME
	 * @return  the value of TB_CRM_BUSINESS.DELETETIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public Date getDeletetime() {
		return deletetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.DELETETIME
	 * @param deletetime  the value for TB_CRM_BUSINESS.DELETETIME
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setDeletetime(Date deletetime) {
		this.deletetime = deletetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.CONTACTSID
	 * @return  the value of TB_CRM_BUSINESS.CONTACTSID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getContactsid() {
		return contactsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.CONTACTSID
	 * @param contactsid  the value for TB_CRM_BUSINESS.CONTACTSID
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setContactsid(String contactsid) {
		this.contactsid = contactsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.CONTRACTADDRESS
	 * @return  the value of TB_CRM_BUSINESS.CONTRACTADDRESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getContractaddress() {
		return contractaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.CONTRACTADDRESS
	 * @param contractaddress  the value for TB_CRM_BUSINESS.CONTRACTADDRESS
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setContractaddress(String contractaddress) {
		this.contractaddress = contractaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_BUSINESS.DESCRIPTION
	 * @return  the value of TB_CRM_BUSINESS.DESCRIPTION
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_BUSINESS.DESCRIPTION
	 * @param description  the value for TB_CRM_BUSINESS.DESCRIPTION
	 * @mbg.generated  Tue Apr 24 16:07:08 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}