package com.zhidisoft.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbCrmLeadsPoolExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public TbCrmLeadsPoolExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLeadsidIsNull() {
            addCriterion("LEADSID is null");
            return (Criteria) this;
        }

        public Criteria andLeadsidIsNotNull() {
            addCriterion("LEADSID is not null");
            return (Criteria) this;
        }

        public Criteria andLeadsidEqualTo(String value) {
            addCriterion("LEADSID =", value, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidNotEqualTo(String value) {
            addCriterion("LEADSID <>", value, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidGreaterThan(String value) {
            addCriterion("LEADSID >", value, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidGreaterThanOrEqualTo(String value) {
            addCriterion("LEADSID >=", value, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidLessThan(String value) {
            addCriterion("LEADSID <", value, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidLessThanOrEqualTo(String value) {
            addCriterion("LEADSID <=", value, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidLike(String value) {
            addCriterion("LEADSID like", value, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidNotLike(String value) {
            addCriterion("LEADSID not like", value, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidIn(List<String> values) {
            addCriterion("LEADSID in", values, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidNotIn(List<String> values) {
            addCriterion("LEADSID not in", values, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidBetween(String value1, String value2) {
            addCriterion("LEADSID between", value1, value2, "leadsid");
            return (Criteria) this;
        }

        public Criteria andLeadsidNotBetween(String value1, String value2) {
            addCriterion("LEADSID not between", value1, value2, "leadsid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridIsNull() {
            addCriterion("OWNERUSERID is null");
            return (Criteria) this;
        }

        public Criteria andOwneruseridIsNotNull() {
            addCriterion("OWNERUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andOwneruseridEqualTo(String value) {
            addCriterion("OWNERUSERID =", value, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridNotEqualTo(String value) {
            addCriterion("OWNERUSERID <>", value, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridGreaterThan(String value) {
            addCriterion("OWNERUSERID >", value, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridGreaterThanOrEqualTo(String value) {
            addCriterion("OWNERUSERID >=", value, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridLessThan(String value) {
            addCriterion("OWNERUSERID <", value, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridLessThanOrEqualTo(String value) {
            addCriterion("OWNERUSERID <=", value, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridLike(String value) {
            addCriterion("OWNERUSERID like", value, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridNotLike(String value) {
            addCriterion("OWNERUSERID not like", value, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridIn(List<String> values) {
            addCriterion("OWNERUSERID in", values, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridNotIn(List<String> values) {
            addCriterion("OWNERUSERID not in", values, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridBetween(String value1, String value2) {
            addCriterion("OWNERUSERID between", value1, value2, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andOwneruseridNotBetween(String value1, String value2) {
            addCriterion("OWNERUSERID not between", value1, value2, "owneruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridIsNull() {
            addCriterion("CREATORUSERID is null");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridIsNotNull() {
            addCriterion("CREATORUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridEqualTo(String value) {
            addCriterion("CREATORUSERID =", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridNotEqualTo(String value) {
            addCriterion("CREATORUSERID <>", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridGreaterThan(String value) {
            addCriterion("CREATORUSERID >", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridGreaterThanOrEqualTo(String value) {
            addCriterion("CREATORUSERID >=", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridLessThan(String value) {
            addCriterion("CREATORUSERID <", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridLessThanOrEqualTo(String value) {
            addCriterion("CREATORUSERID <=", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridLike(String value) {
            addCriterion("CREATORUSERID like", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridNotLike(String value) {
            addCriterion("CREATORUSERID not like", value, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridIn(List<String> values) {
            addCriterion("CREATORUSERID in", values, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridNotIn(List<String> values) {
            addCriterion("CREATORUSERID not in", values, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridBetween(String value1, String value2) {
            addCriterion("CREATORUSERID between", value1, value2, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andCreatoruseridNotBetween(String value1, String value2) {
            addCriterion("CREATORUSERID not between", value1, value2, "creatoruserid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("POSITION is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("POSITION is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("POSITION =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("POSITION <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("POSITION >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("POSITION >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("POSITION <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("POSITION <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("POSITION like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("POSITION not like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<String> values) {
            addCriterion("POSITION in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            addCriterion("POSITION not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("POSITION between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("POSITION not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andContactsnameIsNull() {
            addCriterion("CONTACTSNAME is null");
            return (Criteria) this;
        }

        public Criteria andContactsnameIsNotNull() {
            addCriterion("CONTACTSNAME is not null");
            return (Criteria) this;
        }

        public Criteria andContactsnameEqualTo(String value) {
            addCriterion("CONTACTSNAME =", value, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameNotEqualTo(String value) {
            addCriterion("CONTACTSNAME <>", value, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameGreaterThan(String value) {
            addCriterion("CONTACTSNAME >", value, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameGreaterThanOrEqualTo(String value) {
            addCriterion("CONTACTSNAME >=", value, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameLessThan(String value) {
            addCriterion("CONTACTSNAME <", value, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameLessThanOrEqualTo(String value) {
            addCriterion("CONTACTSNAME <=", value, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameLike(String value) {
            addCriterion("CONTACTSNAME like", value, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameNotLike(String value) {
            addCriterion("CONTACTSNAME not like", value, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameIn(List<String> values) {
            addCriterion("CONTACTSNAME in", values, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameNotIn(List<String> values) {
            addCriterion("CONTACTSNAME not in", values, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameBetween(String value1, String value2) {
            addCriterion("CONTACTSNAME between", value1, value2, "contactsname");
            return (Criteria) this;
        }

        public Criteria andContactsnameNotBetween(String value1, String value2) {
            addCriterion("CONTACTSNAME not between", value1, value2, "contactsname");
            return (Criteria) this;
        }

        public Criteria andSaltnameIsNull() {
            addCriterion("SALTNAME is null");
            return (Criteria) this;
        }

        public Criteria andSaltnameIsNotNull() {
            addCriterion("SALTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andSaltnameEqualTo(String value) {
            addCriterion("SALTNAME =", value, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameNotEqualTo(String value) {
            addCriterion("SALTNAME <>", value, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameGreaterThan(String value) {
            addCriterion("SALTNAME >", value, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameGreaterThanOrEqualTo(String value) {
            addCriterion("SALTNAME >=", value, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameLessThan(String value) {
            addCriterion("SALTNAME <", value, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameLessThanOrEqualTo(String value) {
            addCriterion("SALTNAME <=", value, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameLike(String value) {
            addCriterion("SALTNAME like", value, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameNotLike(String value) {
            addCriterion("SALTNAME not like", value, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameIn(List<String> values) {
            addCriterion("SALTNAME in", values, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameNotIn(List<String> values) {
            addCriterion("SALTNAME not in", values, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameBetween(String value1, String value2) {
            addCriterion("SALTNAME between", value1, value2, "saltname");
            return (Criteria) this;
        }

        public Criteria andSaltnameNotBetween(String value1, String value2) {
            addCriterion("SALTNAME not between", value1, value2, "saltname");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("MOBILE =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("MOBILE <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("MOBILE >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("MOBILE <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("MOBILE <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("MOBILE like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("MOBILE not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("MOBILE in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("MOBILE not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("MOBILE between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("MOBILE not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CREATETIME =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CREATETIME >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CREATETIME <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CREATETIME in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("UPDATETIME =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("UPDATETIME <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("UPDATETIME >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("UPDATETIME <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("UPDATETIME in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("UPDATETIME not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNull() {
            addCriterion("ISDELETED is null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNotNull() {
            addCriterion("ISDELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedEqualTo(Short value) {
            addCriterion("ISDELETED =", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotEqualTo(Short value) {
            addCriterion("ISDELETED <>", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThan(Short value) {
            addCriterion("ISDELETED >", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThanOrEqualTo(Short value) {
            addCriterion("ISDELETED >=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThan(Short value) {
            addCriterion("ISDELETED <", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThanOrEqualTo(Short value) {
            addCriterion("ISDELETED <=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIn(List<Short> values) {
            addCriterion("ISDELETED in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotIn(List<Short> values) {
            addCriterion("ISDELETED not in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedBetween(Short value1, Short value2) {
            addCriterion("ISDELETED between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotBetween(Short value1, Short value2) {
            addCriterion("ISDELETED not between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridIsNull() {
            addCriterion("DELETEUSERID is null");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridIsNotNull() {
            addCriterion("DELETEUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridEqualTo(String value) {
            addCriterion("DELETEUSERID =", value, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridNotEqualTo(String value) {
            addCriterion("DELETEUSERID <>", value, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridGreaterThan(String value) {
            addCriterion("DELETEUSERID >", value, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridGreaterThanOrEqualTo(String value) {
            addCriterion("DELETEUSERID >=", value, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridLessThan(String value) {
            addCriterion("DELETEUSERID <", value, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridLessThanOrEqualTo(String value) {
            addCriterion("DELETEUSERID <=", value, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridLike(String value) {
            addCriterion("DELETEUSERID like", value, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridNotLike(String value) {
            addCriterion("DELETEUSERID not like", value, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridIn(List<String> values) {
            addCriterion("DELETEUSERID in", values, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridNotIn(List<String> values) {
            addCriterion("DELETEUSERID not in", values, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridBetween(String value1, String value2) {
            addCriterion("DELETEUSERID between", value1, value2, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeleteuseridNotBetween(String value1, String value2) {
            addCriterion("DELETEUSERID not between", value1, value2, "deleteuserid");
            return (Criteria) this;
        }

        public Criteria andDeletetimeIsNull() {
            addCriterion("DELETETIME is null");
            return (Criteria) this;
        }

        public Criteria andDeletetimeIsNotNull() {
            addCriterion("DELETETIME is not null");
            return (Criteria) this;
        }

        public Criteria andDeletetimeEqualTo(Date value) {
            addCriterion("DELETETIME =", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeNotEqualTo(Date value) {
            addCriterion("DELETETIME <>", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeGreaterThan(Date value) {
            addCriterion("DELETETIME >", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DELETETIME >=", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeLessThan(Date value) {
            addCriterion("DELETETIME <", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeLessThanOrEqualTo(Date value) {
            addCriterion("DELETETIME <=", value, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeIn(List<Date> values) {
            addCriterion("DELETETIME in", values, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeNotIn(List<Date> values) {
            addCriterion("DELETETIME not in", values, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeBetween(Date value1, Date value2) {
            addCriterion("DELETETIME between", value1, value2, "deletetime");
            return (Criteria) this;
        }

        public Criteria andDeletetimeNotBetween(Date value1, Date value2) {
            addCriterion("DELETETIME not between", value1, value2, "deletetime");
            return (Criteria) this;
        }

        public Criteria andIstransformedIsNull() {
            addCriterion("ISTRANSFORMED is null");
            return (Criteria) this;
        }

        public Criteria andIstransformedIsNotNull() {
            addCriterion("ISTRANSFORMED is not null");
            return (Criteria) this;
        }

        public Criteria andIstransformedEqualTo(Short value) {
            addCriterion("ISTRANSFORMED =", value, "istransformed");
            return (Criteria) this;
        }

        public Criteria andIstransformedNotEqualTo(Short value) {
            addCriterion("ISTRANSFORMED <>", value, "istransformed");
            return (Criteria) this;
        }

        public Criteria andIstransformedGreaterThan(Short value) {
            addCriterion("ISTRANSFORMED >", value, "istransformed");
            return (Criteria) this;
        }

        public Criteria andIstransformedGreaterThanOrEqualTo(Short value) {
            addCriterion("ISTRANSFORMED >=", value, "istransformed");
            return (Criteria) this;
        }

        public Criteria andIstransformedLessThan(Short value) {
            addCriterion("ISTRANSFORMED <", value, "istransformed");
            return (Criteria) this;
        }

        public Criteria andIstransformedLessThanOrEqualTo(Short value) {
            addCriterion("ISTRANSFORMED <=", value, "istransformed");
            return (Criteria) this;
        }

        public Criteria andIstransformedIn(List<Short> values) {
            addCriterion("ISTRANSFORMED in", values, "istransformed");
            return (Criteria) this;
        }

        public Criteria andIstransformedNotIn(List<Short> values) {
            addCriterion("ISTRANSFORMED not in", values, "istransformed");
            return (Criteria) this;
        }

        public Criteria andIstransformedBetween(Short value1, Short value2) {
            addCriterion("ISTRANSFORMED between", value1, value2, "istransformed");
            return (Criteria) this;
        }

        public Criteria andIstransformedNotBetween(Short value1, Short value2) {
            addCriterion("ISTRANSFORMED not between", value1, value2, "istransformed");
            return (Criteria) this;
        }

        public Criteria andTransformuseridIsNull() {
            addCriterion("TRANSFORMUSERID is null");
            return (Criteria) this;
        }

        public Criteria andTransformuseridIsNotNull() {
            addCriterion("TRANSFORMUSERID is not null");
            return (Criteria) this;
        }

        public Criteria andTransformuseridEqualTo(String value) {
            addCriterion("TRANSFORMUSERID =", value, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridNotEqualTo(String value) {
            addCriterion("TRANSFORMUSERID <>", value, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridGreaterThan(String value) {
            addCriterion("TRANSFORMUSERID >", value, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFORMUSERID >=", value, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridLessThan(String value) {
            addCriterion("TRANSFORMUSERID <", value, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridLessThanOrEqualTo(String value) {
            addCriterion("TRANSFORMUSERID <=", value, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridLike(String value) {
            addCriterion("TRANSFORMUSERID like", value, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridNotLike(String value) {
            addCriterion("TRANSFORMUSERID not like", value, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridIn(List<String> values) {
            addCriterion("TRANSFORMUSERID in", values, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridNotIn(List<String> values) {
            addCriterion("TRANSFORMUSERID not in", values, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridBetween(String value1, String value2) {
            addCriterion("TRANSFORMUSERID between", value1, value2, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andTransformuseridNotBetween(String value1, String value2) {
            addCriterion("TRANSFORMUSERID not between", value1, value2, "transformuserid");
            return (Criteria) this;
        }

        public Criteria andContactsidIsNull() {
            addCriterion("CONTACTSID is null");
            return (Criteria) this;
        }

        public Criteria andContactsidIsNotNull() {
            addCriterion("CONTACTSID is not null");
            return (Criteria) this;
        }

        public Criteria andContactsidEqualTo(String value) {
            addCriterion("CONTACTSID =", value, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidNotEqualTo(String value) {
            addCriterion("CONTACTSID <>", value, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidGreaterThan(String value) {
            addCriterion("CONTACTSID >", value, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidGreaterThanOrEqualTo(String value) {
            addCriterion("CONTACTSID >=", value, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidLessThan(String value) {
            addCriterion("CONTACTSID <", value, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidLessThanOrEqualTo(String value) {
            addCriterion("CONTACTSID <=", value, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidLike(String value) {
            addCriterion("CONTACTSID like", value, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidNotLike(String value) {
            addCriterion("CONTACTSID not like", value, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidIn(List<String> values) {
            addCriterion("CONTACTSID in", values, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidNotIn(List<String> values) {
            addCriterion("CONTACTSID not in", values, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidBetween(String value1, String value2) {
            addCriterion("CONTACTSID between", value1, value2, "contactsid");
            return (Criteria) this;
        }

        public Criteria andContactsidNotBetween(String value1, String value2) {
            addCriterion("CONTACTSID not between", value1, value2, "contactsid");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNull() {
            addCriterion("CUSTOMERID is null");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNotNull() {
            addCriterion("CUSTOMERID is not null");
            return (Criteria) this;
        }

        public Criteria andCustomeridEqualTo(String value) {
            addCriterion("CUSTOMERID =", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotEqualTo(String value) {
            addCriterion("CUSTOMERID <>", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThan(String value) {
            addCriterion("CUSTOMERID >", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTOMERID >=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThan(String value) {
            addCriterion("CUSTOMERID <", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThanOrEqualTo(String value) {
            addCriterion("CUSTOMERID <=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLike(String value) {
            addCriterion("CUSTOMERID like", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotLike(String value) {
            addCriterion("CUSTOMERID not like", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridIn(List<String> values) {
            addCriterion("CUSTOMERID in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotIn(List<String> values) {
            addCriterion("CUSTOMERID not in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridBetween(String value1, String value2) {
            addCriterion("CUSTOMERID between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotBetween(String value1, String value2) {
            addCriterion("CUSTOMERID not between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andBusinessidIsNull() {
            addCriterion("BUSINESSID is null");
            return (Criteria) this;
        }

        public Criteria andBusinessidIsNotNull() {
            addCriterion("BUSINESSID is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessidEqualTo(String value) {
            addCriterion("BUSINESSID =", value, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidNotEqualTo(String value) {
            addCriterion("BUSINESSID <>", value, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidGreaterThan(String value) {
            addCriterion("BUSINESSID >", value, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESSID >=", value, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidLessThan(String value) {
            addCriterion("BUSINESSID <", value, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidLessThanOrEqualTo(String value) {
            addCriterion("BUSINESSID <=", value, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidLike(String value) {
            addCriterion("BUSINESSID like", value, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidNotLike(String value) {
            addCriterion("BUSINESSID not like", value, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidIn(List<String> values) {
            addCriterion("BUSINESSID in", values, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidNotIn(List<String> values) {
            addCriterion("BUSINESSID not in", values, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidBetween(String value1, String value2) {
            addCriterion("BUSINESSID between", value1, value2, "businessid");
            return (Criteria) this;
        }

        public Criteria andBusinessidNotBetween(String value1, String value2) {
            addCriterion("BUSINESSID not between", value1, value2, "businessid");
            return (Criteria) this;
        }

        public Criteria andNextstepIsNull() {
            addCriterion("NEXTSTEP is null");
            return (Criteria) this;
        }

        public Criteria andNextstepIsNotNull() {
            addCriterion("NEXTSTEP is not null");
            return (Criteria) this;
        }

        public Criteria andNextstepEqualTo(String value) {
            addCriterion("NEXTSTEP =", value, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepNotEqualTo(String value) {
            addCriterion("NEXTSTEP <>", value, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepGreaterThan(String value) {
            addCriterion("NEXTSTEP >", value, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepGreaterThanOrEqualTo(String value) {
            addCriterion("NEXTSTEP >=", value, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepLessThan(String value) {
            addCriterion("NEXTSTEP <", value, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepLessThanOrEqualTo(String value) {
            addCriterion("NEXTSTEP <=", value, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepLike(String value) {
            addCriterion("NEXTSTEP like", value, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepNotLike(String value) {
            addCriterion("NEXTSTEP not like", value, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepIn(List<String> values) {
            addCriterion("NEXTSTEP in", values, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepNotIn(List<String> values) {
            addCriterion("NEXTSTEP not in", values, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepBetween(String value1, String value2) {
            addCriterion("NEXTSTEP between", value1, value2, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextstepNotBetween(String value1, String value2) {
            addCriterion("NEXTSTEP not between", value1, value2, "nextstep");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeIsNull() {
            addCriterion("NEXTSTEPTIME is null");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeIsNotNull() {
            addCriterion("NEXTSTEPTIME is not null");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeEqualTo(Date value) {
            addCriterion("NEXTSTEPTIME =", value, "nextsteptime");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeNotEqualTo(Date value) {
            addCriterion("NEXTSTEPTIME <>", value, "nextsteptime");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeGreaterThan(Date value) {
            addCriterion("NEXTSTEPTIME >", value, "nextsteptime");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeGreaterThanOrEqualTo(Date value) {
            addCriterion("NEXTSTEPTIME >=", value, "nextsteptime");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeLessThan(Date value) {
            addCriterion("NEXTSTEPTIME <", value, "nextsteptime");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeLessThanOrEqualTo(Date value) {
            addCriterion("NEXTSTEPTIME <=", value, "nextsteptime");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeIn(List<Date> values) {
            addCriterion("NEXTSTEPTIME in", values, "nextsteptime");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeNotIn(List<Date> values) {
            addCriterion("NEXTSTEPTIME not in", values, "nextsteptime");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeBetween(Date value1, Date value2) {
            addCriterion("NEXTSTEPTIME between", value1, value2, "nextsteptime");
            return (Criteria) this;
        }

        public Criteria andNextsteptimeNotBetween(Date value1, Date value2) {
            addCriterion("NEXTSTEPTIME not between", value1, value2, "nextsteptime");
            return (Criteria) this;
        }

        public Criteria andHavetimeIsNull() {
            addCriterion("HAVETIME is null");
            return (Criteria) this;
        }

        public Criteria andHavetimeIsNotNull() {
            addCriterion("HAVETIME is not null");
            return (Criteria) this;
        }

        public Criteria andHavetimeEqualTo(Date value) {
            addCriterion("HAVETIME =", value, "havetime");
            return (Criteria) this;
        }

        public Criteria andHavetimeNotEqualTo(Date value) {
            addCriterion("HAVETIME <>", value, "havetime");
            return (Criteria) this;
        }

        public Criteria andHavetimeGreaterThan(Date value) {
            addCriterion("HAVETIME >", value, "havetime");
            return (Criteria) this;
        }

        public Criteria andHavetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("HAVETIME >=", value, "havetime");
            return (Criteria) this;
        }

        public Criteria andHavetimeLessThan(Date value) {
            addCriterion("HAVETIME <", value, "havetime");
            return (Criteria) this;
        }

        public Criteria andHavetimeLessThanOrEqualTo(Date value) {
            addCriterion("HAVETIME <=", value, "havetime");
            return (Criteria) this;
        }

        public Criteria andHavetimeIn(List<Date> values) {
            addCriterion("HAVETIME in", values, "havetime");
            return (Criteria) this;
        }

        public Criteria andHavetimeNotIn(List<Date> values) {
            addCriterion("HAVETIME not in", values, "havetime");
            return (Criteria) this;
        }

        public Criteria andHavetimeBetween(Date value1, Date value2) {
            addCriterion("HAVETIME between", value1, value2, "havetime");
            return (Criteria) this;
        }

        public Criteria andHavetimeNotBetween(Date value1, Date value2) {
            addCriterion("HAVETIME not between", value1, value2, "havetime");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("SOURCE =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("SOURCE <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("SOURCE >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("SOURCE <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("SOURCE <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("SOURCE like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("SOURCE not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("SOURCE in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("SOURCE not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("SOURCE between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("SOURCE not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andLeadnoteIsNull() {
            addCriterion("LEADNOTE is null");
            return (Criteria) this;
        }

        public Criteria andLeadnoteIsNotNull() {
            addCriterion("LEADNOTE is not null");
            return (Criteria) this;
        }

        public Criteria andLeadnoteEqualTo(String value) {
            addCriterion("LEADNOTE =", value, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteNotEqualTo(String value) {
            addCriterion("LEADNOTE <>", value, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteGreaterThan(String value) {
            addCriterion("LEADNOTE >", value, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteGreaterThanOrEqualTo(String value) {
            addCriterion("LEADNOTE >=", value, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteLessThan(String value) {
            addCriterion("LEADNOTE <", value, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteLessThanOrEqualTo(String value) {
            addCriterion("LEADNOTE <=", value, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteLike(String value) {
            addCriterion("LEADNOTE like", value, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteNotLike(String value) {
            addCriterion("LEADNOTE not like", value, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteIn(List<String> values) {
            addCriterion("LEADNOTE in", values, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteNotIn(List<String> values) {
            addCriterion("LEADNOTE not in", values, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteBetween(String value1, String value2) {
            addCriterion("LEADNOTE between", value1, value2, "leadnote");
            return (Criteria) this;
        }

        public Criteria andLeadnoteNotBetween(String value1, String value2) {
            addCriterion("LEADNOTE not between", value1, value2, "leadnote");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 24 15:25:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CRM_LEADS
     *
     * @mbg.generated Tue Apr 24 15:25:40 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}