package com.zhidisoft.crm.entity;

import java.util.Date;

public class TbCrmContacts {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.CONTACTSID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String contactsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.CREATORUSERID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String creatoruserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.NAME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.POST
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String post;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.DEPARTMENT
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.SEX
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private Short sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.SALTNAME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String saltname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.TELEPHONE
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.EMAIL
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.QQNO
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String qqno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.ADDRESS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.ZIPCODE
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String zipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.DESCRIPTION
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.CREATETIME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.UPDATDTIME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private Date updatdtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.ISDELETED
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private Short isdeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.DELETEUSERID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String deleteuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.DELETETIME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private Date deletetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.CUSTOMERID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String customerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.FIRSTCONTACTSID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private String firstcontactsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_CRM_CONTACTS.ISFIRST
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	private Short isfirst;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.CONTACTSID
	 * @return  the value of TB_CRM_CONTACTS.CONTACTSID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getContactsid() {
		return contactsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.CONTACTSID
	 * @param contactsid  the value for TB_CRM_CONTACTS.CONTACTSID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setContactsid(String contactsid) {
		this.contactsid = contactsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.CREATORUSERID
	 * @return  the value of TB_CRM_CONTACTS.CREATORUSERID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getCreatoruserid() {
		return creatoruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.CREATORUSERID
	 * @param creatoruserid  the value for TB_CRM_CONTACTS.CREATORUSERID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setCreatoruserid(String creatoruserid) {
		this.creatoruserid = creatoruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.NAME
	 * @return  the value of TB_CRM_CONTACTS.NAME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.NAME
	 * @param name  the value for TB_CRM_CONTACTS.NAME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.POST
	 * @return  the value of TB_CRM_CONTACTS.POST
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getPost() {
		return post;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.POST
	 * @param post  the value for TB_CRM_CONTACTS.POST
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setPost(String post) {
		this.post = post;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.DEPARTMENT
	 * @return  the value of TB_CRM_CONTACTS.DEPARTMENT
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.DEPARTMENT
	 * @param department  the value for TB_CRM_CONTACTS.DEPARTMENT
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.SEX
	 * @return  the value of TB_CRM_CONTACTS.SEX
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public Short getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.SEX
	 * @param sex  the value for TB_CRM_CONTACTS.SEX
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setSex(Short sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.SALTNAME
	 * @return  the value of TB_CRM_CONTACTS.SALTNAME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getSaltname() {
		return saltname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.SALTNAME
	 * @param saltname  the value for TB_CRM_CONTACTS.SALTNAME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setSaltname(String saltname) {
		this.saltname = saltname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.TELEPHONE
	 * @return  the value of TB_CRM_CONTACTS.TELEPHONE
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.TELEPHONE
	 * @param telephone  the value for TB_CRM_CONTACTS.TELEPHONE
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.EMAIL
	 * @return  the value of TB_CRM_CONTACTS.EMAIL
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.EMAIL
	 * @param email  the value for TB_CRM_CONTACTS.EMAIL
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.QQNO
	 * @return  the value of TB_CRM_CONTACTS.QQNO
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getQqno() {
		return qqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.QQNO
	 * @param qqno  the value for TB_CRM_CONTACTS.QQNO
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setQqno(String qqno) {
		this.qqno = qqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.ADDRESS
	 * @return  the value of TB_CRM_CONTACTS.ADDRESS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.ADDRESS
	 * @param address  the value for TB_CRM_CONTACTS.ADDRESS
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.ZIPCODE
	 * @return  the value of TB_CRM_CONTACTS.ZIPCODE
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.ZIPCODE
	 * @param zipcode  the value for TB_CRM_CONTACTS.ZIPCODE
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.DESCRIPTION
	 * @return  the value of TB_CRM_CONTACTS.DESCRIPTION
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.DESCRIPTION
	 * @param description  the value for TB_CRM_CONTACTS.DESCRIPTION
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.CREATETIME
	 * @return  the value of TB_CRM_CONTACTS.CREATETIME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.CREATETIME
	 * @param createtime  the value for TB_CRM_CONTACTS.CREATETIME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.UPDATDTIME
	 * @return  the value of TB_CRM_CONTACTS.UPDATDTIME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public Date getUpdatdtime() {
		return updatdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.UPDATDTIME
	 * @param updatdtime  the value for TB_CRM_CONTACTS.UPDATDTIME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setUpdatdtime(Date updatdtime) {
		this.updatdtime = updatdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.ISDELETED
	 * @return  the value of TB_CRM_CONTACTS.ISDELETED
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public Short getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.ISDELETED
	 * @param isdeleted  the value for TB_CRM_CONTACTS.ISDELETED
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setIsdeleted(Short isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.DELETEUSERID
	 * @return  the value of TB_CRM_CONTACTS.DELETEUSERID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getDeleteuserid() {
		return deleteuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.DELETEUSERID
	 * @param deleteuserid  the value for TB_CRM_CONTACTS.DELETEUSERID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setDeleteuserid(String deleteuserid) {
		this.deleteuserid = deleteuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.DELETETIME
	 * @return  the value of TB_CRM_CONTACTS.DELETETIME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public Date getDeletetime() {
		return deletetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.DELETETIME
	 * @param deletetime  the value for TB_CRM_CONTACTS.DELETETIME
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setDeletetime(Date deletetime) {
		this.deletetime = deletetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.CUSTOMERID
	 * @return  the value of TB_CRM_CONTACTS.CUSTOMERID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.CUSTOMERID
	 * @param customerid  the value for TB_CRM_CONTACTS.CUSTOMERID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.FIRSTCONTACTSID
	 * @return  the value of TB_CRM_CONTACTS.FIRSTCONTACTSID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public String getFirstcontactsid() {
		return firstcontactsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.FIRSTCONTACTSID
	 * @param firstcontactsid  the value for TB_CRM_CONTACTS.FIRSTCONTACTSID
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setFirstcontactsid(String firstcontactsid) {
		this.firstcontactsid = firstcontactsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_CRM_CONTACTS.ISFIRST
	 * @return  the value of TB_CRM_CONTACTS.ISFIRST
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public Short getIsfirst() {
		return isfirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_CRM_CONTACTS.ISFIRST
	 * @param isfirst  the value for TB_CRM_CONTACTS.ISFIRST
	 * @mbg.generated  Thu May 03 11:23:26 CST 2018
	 */
	public void setIsfirst(Short isfirst) {
		this.isfirst = isfirst;
	}
}