package com.zhidisoft.crm.entity;

import java.util.Date;

public class TbCrmProductImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.IMAGESID
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    private String imagesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.PRODUCTID
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.ISMAIN
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    private Short ismain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.NAME
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.SAVENAME
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    private String savename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.IMAGESIZE
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    private String imagesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.PATH
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.CREATETIME
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CRM_PRODUCT_IMAGES.SORTNUM
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    private Long sortnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.IMAGESID
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.IMAGESID
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String getImagesid() {
        return imagesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.IMAGESID
     *
     * @param imagesid the value for TB_CRM_PRODUCT_IMAGES.IMAGESID
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public void setImagesid(String imagesid) {
        this.imagesid = imagesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.PRODUCTID
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.PRODUCTID
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.PRODUCTID
     *
     * @param productid the value for TB_CRM_PRODUCT_IMAGES.PRODUCTID
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.ISMAIN
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.ISMAIN
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public Short getIsmain() {
        return ismain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.ISMAIN
     *
     * @param ismain the value for TB_CRM_PRODUCT_IMAGES.ISMAIN
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public void setIsmain(Short ismain) {
        this.ismain = ismain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.NAME
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.NAME
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.NAME
     *
     * @param name the value for TB_CRM_PRODUCT_IMAGES.NAME
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.SAVENAME
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.SAVENAME
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String getSavename() {
        return savename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.SAVENAME
     *
     * @param savename the value for TB_CRM_PRODUCT_IMAGES.SAVENAME
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public void setSavename(String savename) {
        this.savename = savename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.IMAGESIZE
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.IMAGESIZE
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String getImagesize() {
        return imagesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.IMAGESIZE
     *
     * @param imagesize the value for TB_CRM_PRODUCT_IMAGES.IMAGESIZE
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public void setImagesize(String imagesize) {
        this.imagesize = imagesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.PATH
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.PATH
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.PATH
     *
     * @param path the value for TB_CRM_PRODUCT_IMAGES.PATH
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.CREATETIME
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.CREATETIME
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.CREATETIME
     *
     * @param createtime the value for TB_CRM_PRODUCT_IMAGES.CREATETIME
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CRM_PRODUCT_IMAGES.SORTNUM
     *
     * @return the value of TB_CRM_PRODUCT_IMAGES.SORTNUM
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public Long getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CRM_PRODUCT_IMAGES.SORTNUM
     *
     * @param sortnum the value for TB_CRM_PRODUCT_IMAGES.SORTNUM
     *
     * @mbg.generated Thu Apr 26 09:47:15 CST 2018
     */
    public void setSortnum(Long sortnum) {
        this.sortnum = sortnum;
    }
}