package com.zhidisoft.crm.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbSystemRoleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public TbSystemRoleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("CREATETIME is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("CREATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("CREATETIME =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("CREATETIME <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("CREATETIME >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATETIME >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("CREATETIME <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATETIME <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("CREATETIME in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("CREATETIME not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("CREATETIME between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATETIME not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andRolenameIsNull() {
			addCriterion("ROLENAME is null");
			return (Criteria) this;
		}

		public Criteria andRolenameIsNotNull() {
			addCriterion("ROLENAME is not null");
			return (Criteria) this;
		}

		public Criteria andRolenameEqualTo(String value) {
			addCriterion("ROLENAME =", value, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameNotEqualTo(String value) {
			addCriterion("ROLENAME <>", value, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameGreaterThan(String value) {
			addCriterion("ROLENAME >", value, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameGreaterThanOrEqualTo(String value) {
			addCriterion("ROLENAME >=", value, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameLessThan(String value) {
			addCriterion("ROLENAME <", value, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameLessThanOrEqualTo(String value) {
			addCriterion("ROLENAME <=", value, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameLike(String value) {
			addCriterion("ROLENAME like", value, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameNotLike(String value) {
			addCriterion("ROLENAME not like", value, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameIn(List<String> values) {
			addCriterion("ROLENAME in", values, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameNotIn(List<String> values) {
			addCriterion("ROLENAME not in", values, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameBetween(String value1, String value2) {
			addCriterion("ROLENAME between", value1, value2, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenameNotBetween(String value1, String value2) {
			addCriterion("ROLENAME not between", value1, value2, "rolename");
			return (Criteria) this;
		}

		public Criteria andRolenoteIsNull() {
			addCriterion("ROLENOTE is null");
			return (Criteria) this;
		}

		public Criteria andRolenoteIsNotNull() {
			addCriterion("ROLENOTE is not null");
			return (Criteria) this;
		}

		public Criteria andRolenoteEqualTo(String value) {
			addCriterion("ROLENOTE =", value, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteNotEqualTo(String value) {
			addCriterion("ROLENOTE <>", value, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteGreaterThan(String value) {
			addCriterion("ROLENOTE >", value, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteGreaterThanOrEqualTo(String value) {
			addCriterion("ROLENOTE >=", value, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteLessThan(String value) {
			addCriterion("ROLENOTE <", value, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteLessThanOrEqualTo(String value) {
			addCriterion("ROLENOTE <=", value, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteLike(String value) {
			addCriterion("ROLENOTE like", value, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteNotLike(String value) {
			addCriterion("ROLENOTE not like", value, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteIn(List<String> values) {
			addCriterion("ROLENOTE in", values, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteNotIn(List<String> values) {
			addCriterion("ROLENOTE not in", values, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteBetween(String value1, String value2) {
			addCriterion("ROLENOTE between", value1, value2, "rolenote");
			return (Criteria) this;
		}

		public Criteria andRolenoteNotBetween(String value1, String value2) {
			addCriterion("ROLENOTE not between", value1, value2, "rolenote");
			return (Criteria) this;
		}

		public Criteria andSortnumIsNull() {
			addCriterion("SORTNUM is null");
			return (Criteria) this;
		}

		public Criteria andSortnumIsNotNull() {
			addCriterion("SORTNUM is not null");
			return (Criteria) this;
		}

		public Criteria andSortnumEqualTo(Long value) {
			addCriterion("SORTNUM =", value, "sortnum");
			return (Criteria) this;
		}

		public Criteria andSortnumNotEqualTo(Long value) {
			addCriterion("SORTNUM <>", value, "sortnum");
			return (Criteria) this;
		}

		public Criteria andSortnumGreaterThan(Long value) {
			addCriterion("SORTNUM >", value, "sortnum");
			return (Criteria) this;
		}

		public Criteria andSortnumGreaterThanOrEqualTo(Long value) {
			addCriterion("SORTNUM >=", value, "sortnum");
			return (Criteria) this;
		}

		public Criteria andSortnumLessThan(Long value) {
			addCriterion("SORTNUM <", value, "sortnum");
			return (Criteria) this;
		}

		public Criteria andSortnumLessThanOrEqualTo(Long value) {
			addCriterion("SORTNUM <=", value, "sortnum");
			return (Criteria) this;
		}

		public Criteria andSortnumIn(List<Long> values) {
			addCriterion("SORTNUM in", values, "sortnum");
			return (Criteria) this;
		}

		public Criteria andSortnumNotIn(List<Long> values) {
			addCriterion("SORTNUM not in", values, "sortnum");
			return (Criteria) this;
		}

		public Criteria andSortnumBetween(Long value1, Long value2) {
			addCriterion("SORTNUM between", value1, value2, "sortnum");
			return (Criteria) this;
		}

		public Criteria andSortnumNotBetween(Long value1, Long value2) {
			addCriterion("SORTNUM not between", value1, value2, "sortnum");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(BigDecimal value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(BigDecimal value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(BigDecimal value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(BigDecimal value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(BigDecimal value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<BigDecimal> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<BigDecimal> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("UPDATETIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("UPDATETIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("UPDATETIME =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("UPDATETIME <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("UPDATETIME >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATETIME >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("UPDATETIME <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATETIME <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("UPDATETIME in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("UPDATETIME not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("UPDATETIME between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATETIME not between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andCreatebyIsNull() {
			addCriterion("CREATEBY is null");
			return (Criteria) this;
		}

		public Criteria andCreatebyIsNotNull() {
			addCriterion("CREATEBY is not null");
			return (Criteria) this;
		}

		public Criteria andCreatebyEqualTo(String value) {
			addCriterion("CREATEBY =", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotEqualTo(String value) {
			addCriterion("CREATEBY <>", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyGreaterThan(String value) {
			addCriterion("CREATEBY >", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyGreaterThanOrEqualTo(String value) {
			addCriterion("CREATEBY >=", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyLessThan(String value) {
			addCriterion("CREATEBY <", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyLessThanOrEqualTo(String value) {
			addCriterion("CREATEBY <=", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyLike(String value) {
			addCriterion("CREATEBY like", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotLike(String value) {
			addCriterion("CREATEBY not like", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyIn(List<String> values) {
			addCriterion("CREATEBY in", values, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotIn(List<String> values) {
			addCriterion("CREATEBY not in", values, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyBetween(String value1, String value2) {
			addCriterion("CREATEBY between", value1, value2, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotBetween(String value1, String value2) {
			addCriterion("CREATEBY not between", value1, value2, "createby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyIsNull() {
			addCriterion("UPDATEBY is null");
			return (Criteria) this;
		}

		public Criteria andUpdatebyIsNotNull() {
			addCriterion("UPDATEBY is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatebyEqualTo(String value) {
			addCriterion("UPDATEBY =", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyNotEqualTo(String value) {
			addCriterion("UPDATEBY <>", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyGreaterThan(String value) {
			addCriterion("UPDATEBY >", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATEBY >=", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyLessThan(String value) {
			addCriterion("UPDATEBY <", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyLessThanOrEqualTo(String value) {
			addCriterion("UPDATEBY <=", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyLike(String value) {
			addCriterion("UPDATEBY like", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyNotLike(String value) {
			addCriterion("UPDATEBY not like", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyIn(List<String> values) {
			addCriterion("UPDATEBY in", values, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyNotIn(List<String> values) {
			addCriterion("UPDATEBY not in", values, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyBetween(String value1, String value2) {
			addCriterion("UPDATEBY between", value1, value2, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyNotBetween(String value1, String value2) {
			addCriterion("UPDATEBY not between", value1, value2, "updateby");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_SYSTEM_ROLE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SYSTEM_ROLE
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 16 15:36:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}