package com.zhidisoft.crm.entity;

import java.util.Date;

public class TbSystemUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.ID
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.CREATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.EMAIL
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.PASSWORD
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.PHONE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.SALT
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.SORTNUM
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private Long sortnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.STATUS
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private Long status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.UPDATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.USERNOTE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String usernote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.USERNAME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.CREATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String createby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.UPDATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String updateby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_USER.ROLE_ID
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.ID
	 * @return  the value of TB_SYSTEM_USER.ID
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.ID
	 * @param id  the value for TB_SYSTEM_USER.ID
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.CREATETIME
	 * @return  the value of TB_SYSTEM_USER.CREATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.CREATETIME
	 * @param createtime  the value for TB_SYSTEM_USER.CREATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.EMAIL
	 * @return  the value of TB_SYSTEM_USER.EMAIL
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.EMAIL
	 * @param email  the value for TB_SYSTEM_USER.EMAIL
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.PASSWORD
	 * @return  the value of TB_SYSTEM_USER.PASSWORD
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.PASSWORD
	 * @param password  the value for TB_SYSTEM_USER.PASSWORD
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.PHONE
	 * @return  the value of TB_SYSTEM_USER.PHONE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.PHONE
	 * @param phone  the value for TB_SYSTEM_USER.PHONE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.SALT
	 * @return  the value of TB_SYSTEM_USER.SALT
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.SALT
	 * @param salt  the value for TB_SYSTEM_USER.SALT
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.SORTNUM
	 * @return  the value of TB_SYSTEM_USER.SORTNUM
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public Long getSortnum() {
		return sortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.SORTNUM
	 * @param sortnum  the value for TB_SYSTEM_USER.SORTNUM
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setSortnum(Long sortnum) {
		this.sortnum = sortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.STATUS
	 * @return  the value of TB_SYSTEM_USER.STATUS
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public Long getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.STATUS
	 * @param status  the value for TB_SYSTEM_USER.STATUS
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setStatus(Long status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.UPDATETIME
	 * @return  the value of TB_SYSTEM_USER.UPDATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.UPDATETIME
	 * @param updatetime  the value for TB_SYSTEM_USER.UPDATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.USERNOTE
	 * @return  the value of TB_SYSTEM_USER.USERNOTE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getUsernote() {
		return usernote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.USERNOTE
	 * @param usernote  the value for TB_SYSTEM_USER.USERNOTE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setUsernote(String usernote) {
		this.usernote = usernote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.USERNAME
	 * @return  the value of TB_SYSTEM_USER.USERNAME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.USERNAME
	 * @param username  the value for TB_SYSTEM_USER.USERNAME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.CREATEBY
	 * @return  the value of TB_SYSTEM_USER.CREATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getCreateby() {
		return createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.CREATEBY
	 * @param createby  the value for TB_SYSTEM_USER.CREATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setCreateby(String createby) {
		this.createby = createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.UPDATEBY
	 * @return  the value of TB_SYSTEM_USER.UPDATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getUpdateby() {
		return updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.UPDATEBY
	 * @param updateby  the value for TB_SYSTEM_USER.UPDATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setUpdateby(String updateby) {
		this.updateby = updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_USER.ROLE_ID
	 * @return  the value of TB_SYSTEM_USER.ROLE_ID
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_USER.ROLE_ID
	 * @param roleId  the value for TB_SYSTEM_USER.ROLE_ID
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}
}