package com.zhidisoft.crm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TbSystemRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_ROLE.ID
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_ROLE.CREATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_ROLE.ROLENAME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String rolename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_ROLE.ROLENOTE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String rolenote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_ROLE.SORTNUM
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private Long sortnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_ROLE.STATUS
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private BigDecimal status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_ROLE.UPDATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_ROLE.CREATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String createby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_SYSTEM_ROLE.UPDATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	private String updateby;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_ROLE.ID
	 * @return  the value of TB_SYSTEM_ROLE.ID
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_ROLE.ID
	 * @param id  the value for TB_SYSTEM_ROLE.ID
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_ROLE.CREATETIME
	 * @return  the value of TB_SYSTEM_ROLE.CREATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_ROLE.CREATETIME
	 * @param createtime  the value for TB_SYSTEM_ROLE.CREATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_ROLE.ROLENAME
	 * @return  the value of TB_SYSTEM_ROLE.ROLENAME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getRolename() {
		return rolename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_ROLE.ROLENAME
	 * @param rolename  the value for TB_SYSTEM_ROLE.ROLENAME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_ROLE.ROLENOTE
	 * @return  the value of TB_SYSTEM_ROLE.ROLENOTE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getRolenote() {
		return rolenote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_ROLE.ROLENOTE
	 * @param rolenote  the value for TB_SYSTEM_ROLE.ROLENOTE
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setRolenote(String rolenote) {
		this.rolenote = rolenote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_ROLE.SORTNUM
	 * @return  the value of TB_SYSTEM_ROLE.SORTNUM
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public Long getSortnum() {
		return sortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_ROLE.SORTNUM
	 * @param sortnum  the value for TB_SYSTEM_ROLE.SORTNUM
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setSortnum(Long sortnum) {
		this.sortnum = sortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_ROLE.STATUS
	 * @return  the value of TB_SYSTEM_ROLE.STATUS
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public BigDecimal getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_ROLE.STATUS
	 * @param status  the value for TB_SYSTEM_ROLE.STATUS
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_ROLE.UPDATETIME
	 * @return  the value of TB_SYSTEM_ROLE.UPDATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_ROLE.UPDATETIME
	 * @param updatetime  the value for TB_SYSTEM_ROLE.UPDATETIME
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_ROLE.CREATEBY
	 * @return  the value of TB_SYSTEM_ROLE.CREATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getCreateby() {
		return createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_ROLE.CREATEBY
	 * @param createby  the value for TB_SYSTEM_ROLE.CREATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setCreateby(String createby) {
		this.createby = createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_SYSTEM_ROLE.UPDATEBY
	 * @return  the value of TB_SYSTEM_ROLE.UPDATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public String getUpdateby() {
		return updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_SYSTEM_ROLE.UPDATEBY
	 * @param updateby  the value for TB_SYSTEM_ROLE.UPDATEBY
	 * @mbg.generated  Mon Apr 16 15:36:27 CST 2018
	 */
	public void setUpdateby(String updateby) {
		this.updateby = updateby;
	}
}