package com.zhidisoft.crm.entity;

import java.util.ArrayList;
import java.util.List;

public class TbSystemRoleFunctionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public TbSystemRoleFunctionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRoleidIsNull() {
			addCriterion("ROLEID is null");
			return (Criteria) this;
		}

		public Criteria andRoleidIsNotNull() {
			addCriterion("ROLEID is not null");
			return (Criteria) this;
		}

		public Criteria andRoleidEqualTo(String value) {
			addCriterion("ROLEID =", value, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidNotEqualTo(String value) {
			addCriterion("ROLEID <>", value, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidGreaterThan(String value) {
			addCriterion("ROLEID >", value, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidGreaterThanOrEqualTo(String value) {
			addCriterion("ROLEID >=", value, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidLessThan(String value) {
			addCriterion("ROLEID <", value, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidLessThanOrEqualTo(String value) {
			addCriterion("ROLEID <=", value, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidLike(String value) {
			addCriterion("ROLEID like", value, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidNotLike(String value) {
			addCriterion("ROLEID not like", value, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidIn(List<String> values) {
			addCriterion("ROLEID in", values, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidNotIn(List<String> values) {
			addCriterion("ROLEID not in", values, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidBetween(String value1, String value2) {
			addCriterion("ROLEID between", value1, value2, "roleid");
			return (Criteria) this;
		}

		public Criteria andRoleidNotBetween(String value1, String value2) {
			addCriterion("ROLEID not between", value1, value2, "roleid");
			return (Criteria) this;
		}

		public Criteria andFuncidIsNull() {
			addCriterion("FUNCID is null");
			return (Criteria) this;
		}

		public Criteria andFuncidIsNotNull() {
			addCriterion("FUNCID is not null");
			return (Criteria) this;
		}

		public Criteria andFuncidEqualTo(String value) {
			addCriterion("FUNCID =", value, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidNotEqualTo(String value) {
			addCriterion("FUNCID <>", value, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidGreaterThan(String value) {
			addCriterion("FUNCID >", value, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidGreaterThanOrEqualTo(String value) {
			addCriterion("FUNCID >=", value, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidLessThan(String value) {
			addCriterion("FUNCID <", value, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidLessThanOrEqualTo(String value) {
			addCriterion("FUNCID <=", value, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidLike(String value) {
			addCriterion("FUNCID like", value, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidNotLike(String value) {
			addCriterion("FUNCID not like", value, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidIn(List<String> values) {
			addCriterion("FUNCID in", values, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidNotIn(List<String> values) {
			addCriterion("FUNCID not in", values, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidBetween(String value1, String value2) {
			addCriterion("FUNCID between", value1, value2, "funcid");
			return (Criteria) this;
		}

		public Criteria andFuncidNotBetween(String value1, String value2) {
			addCriterion("FUNCID not between", value1, value2, "funcid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
	 * @mbg.generated  Sat Apr 21 14:44:20 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SYSTEM_ROLE_FUNCTION
     *
     * @mbg.generated do_not_delete_during_merge Sat Apr 21 14:43:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}